### ISSUE TITLE
[bug] app zooms-in in fullscreen after opening a link

### ISSUE THREAD

**Issue by LintharC** [futo-org/grayjay-android#568] opened 2023-12-24 19:21 UTC
Happens on Samsung S22.

Steps to reproduce:
1. Copy a link to a youtube video (in my case it's usually the 'youtu.be' format)
2. Open grayjay app (usually brand new instance in my case, i.e. not a recent app).
3. From home tab press the search button in the upper right corner.
4. Paste the link and confirm (since a few updates ago the app now directly opens the video, skipping the 'search results' and saving a click, thanks for that!).
5. When the video starts playing, press the fullscreen button in the lower right.
6. The video is now a bit zoomed-in, and since the app has no support for zooming in or out by pinching with 2 fingers, it's stuck that way. Easiest way to notice that is if you have captions enabled, their second row is cut-off, but can also be noticed by the fullscreen button in lower right being also cut. Going out of fullscreen, everything's back to normal, but if you try to go back into the fullscreen, the bug is back. It's actually not just the video zoomed-in, but the app itself, cause if you try to go into video's options, you can see the subtitles options are cut off too. 

![Screenshot_20231224-201359_Grayjay](https://github.com/futo-org/grayjay-android/assets/72015244/459bb19b-effc-454e-91d9-1f086a75b891)
![Screenshot_20231224-201445_Grayjay](https://github.com/futo-org/grayjay-android/assets/72015244/d7fb93b3-c4c7-4a20-9960-8048632184ae)

Has been happening for a month or two now throughout a number of updates, but since that's basically how long I've been using this app, I can't say if it ever worked properly. I also have the android's auto screen rotation usually turned off so it stays in portrait by default.
Going into any video from grayjay's home screen, the fullscreen works as normal.

**Comment by xephos1one** [comment] 2023-12-27 17:23
Duplicate of #293

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:48
Duplicate of #221.

**Closed by Zvonimir-FUTO** 2024-09-24 19:48 UTC
Labels: Bug, Duplicate, UI/UX, Youtube
