### ISSUE TITLE
Unable to cast live streams

### ISSUE THREAD

**Issue by scoostraw** [futo-org/grayjay-android#332] opened 2023-11-18 03:12 UTC
Since the beginning, I have yet to be able to cast a live stream. There are no error messages. It just doesn't work.

**Comment by koen-futo** [comment] 2023-11-20 11:36
I can confirm it works on FCast Receiver, just Chromecast seems to be throwing error 311 "Failed to retrieve the master playlist m3u8 file with three retries." even though the URL is accessible.

**Comment by koen-futo** [comment] 2023-11-21 15:12
Made a fix for ChromeCast that at least allows YouTube live streams to be casted. This will be released in the next release. I will continue working on fixes for Twitch, Kick, etc.

**Comment by koen-futo** [comment] 2023-11-22 08:28
Additionally, made fixes for Twitch, Kick and hopefully other platforms will now also work. Twitch has another issue though and that is the streams are choppy. Opened a new issue for this #357

**Closed by koen-futo** 2023-11-22 08:27 UTC
