### ISSUE TITLE
Fullscreen / Landscape Interface Problem 

### ISSUE THREAD

**Issue by Allvaldrsson** [futo-org/grayjay-android#293] opened 2023-11-13 01:45 UTC
When viewing in landscape mode, the interface controls do not fit the screen. The maximize/minimize button is barely useable and the video progress bar isn't visible.

_Edit: issue happens intermittently, unsure how to consistently duplicate the problem_

_Edit 2: it isn't just the interface but the screen as a whole. I was watching a video with in-video subtitles and the caption was cutoff the screen when this issue occured. I have to close the app and reload the video to view everything once again in landscape mode._

![Screenshot_20231112-193318](https://github.com/futo-org/grayjay-android/assets/106565484/6ab57fa0-1f14-4f53-95e2-b636e9f3357d)

Pixel 6a
Android 14
GrayJay app version 193

**Comment by Allvaldrsson** [comment] 2023-12-01 14:22
I believe sstundzia has figured it out. I was able to replicate the issue, several times in a row, by loading different videos through links pasted into the search bar. Closing the video then reopening it via History presents the video and UI in an aspect ratio that correctly fits the screen.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:48
Duplicate of #221.

**Closed by Zvonimir-FUTO** 2024-09-24 19:48 UTC
Labels: Bug, Duplicate, UI/UX, Youtube
