### ISSUE TITLE
Feature Request: Auto-Resume videos

### ISSUE THREAD

**Issue by BakuretsuEnjoyer** [futo-org/grayjay-android#1035] opened 2024-05-26 15:02 UTC
In my opinion there should be an option for toggling videos to resume automatically. Right now users have a time frame of a couple seconds to click on a "resume at xx:xx:xx" prompt in order to resume a video. 
![screenshot2](https://github.com/futo-org/grayjay-android/assets/161247575/92f99d54-a586-4b01-bf3b-2a485cb8bdb6)

This toggle should exclude music-plugins such as SoundCloud. Music videos from YouTube could be excluded from this by requesting information about the content category from YouTube.
<img width="738" alt="screenshot" src="https://github.com/futo-org/grayjay-android/assets/161247575/ea13dda5-506b-42a9-be48-21e168372762">

**Comment by lmsalustri** [comment] 2024-07-23 07:38
Duplicate of #400

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 17:27
Duplicate of #400.

**Closed by Zvonimir-FUTO** 2024-09-25 17:27 UTC
Labels: Duplicate, Enhancement, UI/UX
