### ISSUE TITLE
V8ValueNull Casting Error opening nested YouTube Comments

### ISSUE THREAD

**Issue by Kevinf63** [futo-org/grayjay-android#477] opened 2023-12-10 14:56 UTC
How I recreate the issue:
- Update existing Grayjay install to release type version 210
- use official YouTube Plugin version 154
- Default comment section is the platform
- Visit any video with replies to top comments
- Expand replies to top comments to see error

![IMG_20231210_145204](https://github.com/futo-org/grayjay-android/assets/3584482/fee76694-efec-422f-bc79-562042a0f41b)
(Comment intentionally pixelated)

Could not submit logs despite setting to verbose (#478).

Clearing app cache (without clearing data) within my RealMe GT Neo 2 phone settings resolves the issue on ColorOS/Android OS 13.

![Screenshot_2023-12-10-15-08-01-44_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/futo-org/grayjay-android/assets/3584482/ed100a32-d8f4-4f41-8e26-09952568d283)

**Comment by Kelvin-FUTO** [comment] 2023-12-11 18:43
Been testing a bit, I've managed to reproduce it once, but not with my dev tools attached.
I suspect Youtube is doing a staged roll out of a new change related to replies. This only causes this to occasionally happen. (Clearing cache should generally not be required, restarting the app might affect it already)
Soon I'll be able to reproduce it more reliably most likely.
Should be a fairly simple fix when I do get it reproduced.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 19:27
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Closed by Zvonimir-FUTO** 2024-09-25 19:27 UTC
Labels: Bug, Youtube
