### ISSUE TITLE
[Feature request] Sort and Search for downloads 

### ISSUE THREAD

**Issue by bruceschaff** [futo-org/grayjay-android#795] opened 2024-02-12 19:43 UTC
I have a lot of videos downloaded and they seem to me sorted randomly, would be great if you can chose how they're sorted and even cooler if you could search downloads.

**Comment by dimyself** [comment] 2024-02-20 18:03
Yes, sorting in downloads and playlists would be very beneficial!

This request was only opened last week? I'm surprised if there hasn't been some before this one

**Comment by Bouhnosaure** [comment] 2024-03-24 12:15
Yes, it's a feature I've been looking for ! 

At least as a temporary placeholder, it could be great to sort by release date from the oldest to newest so, series or videos in multiple parts are not placed in random order.

**Comment by Bouhnosaure** [comment] 2024-03-24 12:20
It should be simple to implement in a fixed sort at first

I'm not a Kotlin developer but it may be possible to sort here :

https://github.com/futo-org/grayjay-android/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Ffuto%2Fplatformplayer%2Ffragment%2Fmainactivity%2Fmain%2FDownloadsFragment.kt#L146

There should be a timestamp property inside the downloaded videos objects

**Comment by dimyself** [comment] 2024-05-05 19:39
At minimum... Sorting (and also maybe searching) is needed for: downloads, playlists, and watch later.

These categories are almost unusable without proper sorting and a way to find videos. 

Downloads are only usable to me because I will download a video in my sub feed and click on it to watch from my sub feed... Forget about finding a downloaded video through the downloads tab

Same for playlists and watch later! I don't even use watch later because all the videos seem to be in a random order with no way to find anything. 

Playlist videos are the same... in a random order with no way to find videos other than manually scrolling / looking / hoping to find what you're looking for.

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:59
Duplicate of #78

**Closed by Zvonimir-FUTO** 2024-09-22 20:59 UTC
Labels: Duplicate, Enhancement, UI
