### ISSUE TITLE
Won't Stream to AirPlay TV WebOS

### ISSUE THREAD

**Issue by talkinggoat** [futo-org/grayjay-android#1258] opened 2024-08-22 02:55 UTC
### What happened?

GreyJay can't stream to webos, AirPlay enabled devices but other apps have no issue and connect immediately. The device shows up but never connects, under GreyJay. I also get an error about YouTube blocking attempts. Both issues happen, no matter the plugin. This is an Android OS v12.

![Screenshot_20240821-214949](https://github.com/user-attachments/assets/df4260b8-0a30-4645-a690-47072721d84b)
![Screenshot_20240821-212336](https://github.com/user-attachments/assets/0730cf20-921f-4ffd-8872-035e55e09c4b)

![Screenshot_20240821-215956](https://github.com/user-attachments/assets/7b5fc16b-79b6-4b53-a71f-db5351aa2dfe)

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
N/A
```

**Comment by codebymatter** [comment] 2024-08-22 19:29
If you've reqd the Grayjay FAQs page, there is a mention of AirPlay support being un reliable / not functioning. It goes like this:

FCast > ChromeCast > AirPlay

Ordered from functioning to least functioning.

**Comment by support-grayjay** [comment] 2024-10-30 19:15
Unfortunately AirPlay is unreliable most of time and it's not Grayjay's fault. Closing issue.

**Closed by support-grayjay** 2024-10-30 19:15 UTC
Labels: Bug, Casting

**Comment by xephos1one** [comment] 2025-06-20 11:40
> Unfortunately AirPlay is unreliable most of time and it's not Grayjay's fault. Closing issue.

Shouldn't AirPlay be removed from Grayjay then if it won't work by design?

**Comment by Zvonimir-FUTO** [comment] 2025-06-20 12:14
We have plans on working on Airplay 2 support in future.
