### ISSUE TITLE
YouTube home content unrelated 

### ISSUE THREAD

**Issue by LordWiggle** [futo-org/grayjay-android#1162] opened 2024-07-17 23:14 UTC
### What happened?

Since the update before the recent one, the "home" tab features completely unrelated junk videos. Before that it gave videos based on my interests and followed channels just like the youtube home page, now it's just the most popular videos (shorts in general). The "home" tab became completely useless. I'm logged in to my YouTube account. 

### Grayjay Version

Latest

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

Laterst

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by lmsalustri** [comment] 2024-07-17 23:35
Duplicate of #250

**Comment by lmsalustri** [comment] 2024-07-17 23:37
Duplicate of #952

**Comment by SevastianGit** [comment] 2024-07-18 22:39
Please close this replicate issue. I also commented a workaround I always use in #952 :D

**Comment by lmsalustri** [comment] 2024-07-18 23:40
Unfortunately this repo is unmoderated. @LordWiggle

**Comment by SevastianGit** [comment] 2024-07-18 23:53
> Unfortunately this repo is unmoderated. @LordWiggle

Yeah, it's a shame, I'd gladly volunteer in any way.
I don't want them to get spammed or anything, but I found their old feedback email to be a lot more effective for reporting bugs and issues, in Grayjay's earleir days at least.

**Comment by lmsalustri** [comment] 2024-07-19 00:29
> > Unfortunately this repo is unmoderated. @LordWiggle
> 
> Yeah, it's a shame, I'd gladly volunteer in any way. I don't want them to get spammed or anything, but I found their old feedback email to be a lot more effective for reporting bugs and issues, in Grayjay's earleir days at least.

Same. I was gonna join the matrix group, but the bot just falsely detected me as a bot and autobanned me...

**Comment by LordWiggle** [comment] 2024-07-19 09:37
> Please close this replicate issue. I also commented a workaround I always use in #952 :D

Thanks!

**Closed** 2024-07-19 09:38 UTC
Labels: Youtube
