### ISSUE TITLE
[Feature request] Implement Platfrom History (progress) Sync

### ISSUE THREAD

**Issue by IlfirinPL** [futo-org/grayjay-android#708] opened 2024-01-18 11:43 UTC
For videos without internal progress bar pull progress bar from other platforms.

This would allow easier switch and continue from watching on pc. And allow to skip already watched

**Comment by lolguy91** [comment] 2024-01-19 18:24
:+1:  would be great yeah

**Comment by Zvonimir-FUTO** [comment] 2024-12-27 13:41
Duplicate of #180.

**Closed by Zvonimir-FUTO** 2024-12-27 13:41 UTC
Labels: Duplicate, Enhancement, All
