### ISSUE TITLE
Provide updates via f-droid rather than in-app updates

### ISSUE THREAD

**Issue by vincentvd1** [futo-org/grayjay-android#1063] opened 2024-06-09 08:10 UTC
I use Grayjay via F-droid. After opening the Grayjay app, it immediatly asked for an update. F-droid didn't indicate there was an update.  My request is therefore if updates can just be provided via F-droid. I personally don't matter if it takes a bit longer for the update to be available then.

Non-techy people might see this current in-app update behaviour as shady.

**Comment by VoxelPrismatic** [comment] 2024-06-10 00:06
I think it takes a moment to propogate everywhere. The latest version, 242, is already on F-Droid.

**Comment by vincentvd1** [comment] 2024-06-10 16:52
> I think it takes a moment to propogate everywhere. The latest version, 242, is already on F-Droid.

I understand that and I have no problem waiting a few days before an update is available. However, the app should not offer in-app update (or atleast not enable them by default). I was a bit reluctant to do that at first. It makes the app feel shady as if it is trying to install shady stuff outside of the appstore.

**Comment by Phil12026** [comment] 2024-06-12 03:45
Why not have the option for it in the settings? default on updates outside the stores is off but it's possible to turn it on for those who want the APK directly?

**Comment by MrRulf** [comment] 2024-07-16 21:07
all the other sources (apk, google play) seem to be on version 249 now while fdroid is still on 242, is there any technical reason for that or just no time/forgotten?

**Comment by grayjay-support-FUTO** [comment] 2024-10-02 22:04
Duplicate of #962.

**Closed by grayjay-support-FUTO** 2024-10-02 22:04 UTC
Labels: Duplicate, Enhancement
