### ISSUE TITLE
Youtube plugin loops video after detected blocking atempt

### ISSUE THREAD

**Issue by jiweigert** [futo-org/grayjay-android#1209] opened 2024-08-01 18:24 UTC
### What happened?

YouTube Videos start from scratch after 10-15 sek of play and after second detected blocking attempt from yiutube

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

188

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by jiweigert** [comment] 2024-08-01 18:25
Android version 13
Mobile RealMe 8

**Comment by somewhiteguy** [comment] 2024-08-02 02:40
Plays the first 25 seconds, then replays from the start.
Reinstalled/updated plugin, and issue remains.

**Comment by lmsalustri** [comment] 2024-08-02 03:35
Duplicate of #1188, please close @jiweigert (Repo is unmoderated)

**Comment by support-grayjay** [comment] 2024-10-29 19:12
Duplicate of #1188.

**Closed by support-grayjay** 2024-10-29 19:12 UTC
Labels: Bug, Duplicate, Youtube
