### ISSUE TITLE
Two of the same Channels in Subscriptions tab

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#413] opened 2023-11-28 20:53 UTC
Hello I went to Subscriptions and found two  rossmanngroup channels.
platform player version 201
![Screenshot_20231128-113250_Grayjay](https://github.com/futo-org/grayjay-android/assets/34012548/81e7082a-fbd6-490d-88da-7fd1c6dc37d7)

**Comment by Kelvin-FUTO** [comment] 2023-11-28 20:58
I assume you subscribed to Louis on both Odysee and Youtube or something?
I suspect that would cause this.
It is not neccesary to subscribe to multiple platforms if the creator has Harbor/Polycentric configured.
That being said, this is indeed a bug and it should deduplicate them.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 18:10
Duplicate of #244.

**Closed by Zvonimir-FUTO** 2024-09-25 18:10 UTC
Labels: Bug, Duplicate, UI/UX, Polycentric
