### ISSUE TITLE
No videos load when filtering out watched videos in a group

### ISSUE THREAD

**Issue by vfosnar** [futo-org/grayjay-android#1361] opened 2024-09-25 21:43 UTC
### What happened?

I have a group of creators, when I switch to the group view Grayjay doesn't fetch enough pages to show any content at all, probably because the first page is fully watched and gets filtered out.

I can bypass this by showing watched videos, sctolling for a while to fetch unwatched vids and enable filtering again.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-11-19 22:23
Appears to be a duplicate of #1245. Correct me if I'm wrong.

**Closed by Zvonimir-FUTO** 2024-11-19 22:23 UTC
Labels: Bug, Duplicate, UI/UX, All
