### ISSUE TITLE
[Issue] portrait mode

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#297] opened 2023-11-13 16:36 UTC
The videos those published in portrait mode by default (short videos) cant fullscreen . Grayjay assumes they as normal yt video and ruins the view @Kelvin-FUTO

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:54
Duplicate of #116.

**Closed by Zvonimir-FUTO** 2024-09-24 19:54 UTC
Labels: Bug, Duplicate, UI/UX, Youtube
