### ISSUE TITLE
age restricted 

### ISSUE THREAD

**Issue by kj2900** [futo-org/grayjay-android#1270] opened 2024-08-27 12:20 UTC
### What happened?

All of sudden i can't watch age restricted content anymore as i could do about a month ago

![Screenshot_2024-08-24-08-11-01-54_ca2ad563b57b5497046450f16b7718e2](https://github.com/user-attachments/assets/ee39134b-ec7d-4cd8-90d8-8daa0b6fd0ec)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

192

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
What happened with age restricted videos all of sudden i need to login now wilde a month ago you could just watch age restricted content just fine

And yes i have turned age restricted mode on and also allow controversial age restricted mode on 

Android 12
```

**Comment by codebymatter** [comment] 2024-08-28 17:10
I tested the Privacy Mode and attempted to simulate your result and the reaaon for it is aa stated. The issue isn't really plugin-suded rather YouTube enforcing a login in ordsr to watch age-restricted.

"But I have Watch Age-Restricted Videos and Cobtroveesial Videos both On."
Technically you should be able to but this reminded of an issue I had with Vanced years ago. I tried watching a music video but was met with a "Must Sign-in" message, which was funny but managed to watch it through another uploader.

Note that having Privacy Mode on, means thar Spotify plugin doesn't work at all as an account is needed to atream music. For live chats, you won't be able to unless you sign in, needing to remove the Privacy Mode.

Not sure if FUTO can circumvebt the age-check YT have in place and bo clue if ReVanced can bypass checks and play..

**Comment by usertoroot** [comment] 2024-09-03 21:00
Hey, did you make sure to toggle "Allow Age Restricted" in the YouTube settings? Go to Sources -> YouTube and it should be there. If it is affected by Privacy Mode that is a bug.

**Comment by kj2900** [comment] 2024-09-04 08:22
Usertoroot

Yes i did toggle them on and still happening even on the latest plugin witch is 194 and app version 259

**Comment by anuragtyagi-dev** [comment] 2024-09-04 08:46
> Hey, did you make sure to toggle "Allow Age Restricted" in the YouTube settings? Go to Sources -> YouTube and it should be there. If it is affected by Privacy Mode that is a bug.

Are you able to watch any ' age restricted ' content? And if yes , then in which setting.

**Comment by usertoroot** [comment] 2024-09-04 09:03
Was able to reproduce, fixed it.

**Comment by usertoroot** [comment] 2024-09-04 09:03
Deploying now.

**Comment by usertoroot** [comment] 2024-09-04 11:45
Please close if fixed

**Comment by kj2900** [comment] 2024-09-05 07:40
Thanks it's working now thanks for the quick messages 🙂

**Comment by that404nerd** [comment] 2024-09-06 12:25
> Thanks it's working now thanks for the quick messages 🙂

Please close this issue. Thanks!

**Closed** 2024-09-06 17:58 UTC
Labels: Youtube
