### ISSUE TITLE
Intra-Playlist Sorting

### ISSUE THREAD

**Issue by Stormer13** [futo-org/grayjay-android#1490] opened 2024-11-18 08:29 UTC
### Use Cases

Playlists in GrayJay can only be sorted and reorganized manually, wasting time if a user wishes to use a particular, common sorting method.

### Proposal

Include a way to sort playlists by things like date published and name of video while still allowing custom sorting to occur.

**Comment by Zvonimir-FUTO** [comment] 2024-11-18 08:43
Duplicate of #78.

**Closed by Zvonimir-FUTO** 2024-11-18 08:43 UTC
Labels: Duplicate, Enhancement, UI/UX, Playlists
