### ISSUE TITLE
[Quality of Life] Setting to change behavior on closing PiP to continue playing in background. 

### ISSUE THREAD

**Issue by apoapostolov** [futo-org/grayjay-android#396] opened 2023-11-26 09:56 UTC
A setting that changes the behavior upon closing the PiP stream, from stopping the video to switching to continue playing in background. Too often close of PiP is on mistake by dragging down, or screen space is needed but the video audio is still important to continue listening.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 17:21
Duplicate of #181.

**Closed by Zvonimir-FUTO** 2024-09-25 17:21 UTC
Labels: Duplicate, Enhancement, UI/UX
