### ISSUE TITLE
[feature request] Remove played video's from showing in home list

### ISSUE THREAD

**Issue by Rundervinkje** [futo-org/grayjay-android#514] opened 2023-12-17 14:03 UTC
Hello,
I would like the option to automatically remove video's from the home feed list when they're (closed to) being finished, so the home list isn't cluttered with alreay watched video's.
Thank you.

**Comment by yzfreestylr** [comment] 2023-12-17 17:31
+1

**Comment by birdup000** [comment] 2023-12-17 17:34
+1

**Comment by CroatZ** [comment] 2024-01-20 12:14
Please, please, please 🙏

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 20:11
Duplicate of #189.

**Closed by Zvonimir-FUTO** 2024-09-25 20:11 UTC
Labels: Duplicate, Enhancement, UI/UX

**Comment by LWaal** [comment] 2024-09-26 16:03
@Zvonimir-FUTO. I hope you appreciate me saying this, cause I mean it well: two out of three QoL tickets have been resolved regarding my tablet. Thank you! I will start paying for the software now.

**Comment by Zvonimir-FUTO** [comment] 2024-09-26 18:46
> @Zvonimir-FUTO. I hope you appreciate me saying this, cause I mean it well: two out of three QoL tickets have been resolved regarding my tablet. Thank you! I will start paying for the software now.

We all appreciate it very much and all the issues reported and enhancement ideas and we will eventually get through all of them with time :)
