### ISSUE TITLE
Videos cut off at last second

### ISSUE THREAD

**Issue by Thatstinkyguy** [futo-org/grayjay-android#459] opened 2023-12-08 10:34 UTC
At the last seconds of a video I was watching, it abruptly cut at the end mid closing word. I checked to see if it was an editing mistake of the creator, but it was fine on the regular YouTube app.

Here's the one in question (I was watching it through Grayjay): https://www.youtube.com/watch?v=SuU_wi0Udyc

Thanks for your time.

**Comment by McIrco95** [comment] 2023-12-08 11:52
Duplicate of #36

**Comment by Thatstinkyguy** [comment] 2023-12-08 14:39
> Duplicate of #36

Didn't catch that. Thanks for telling me.

**Closed** 2023-12-08 14:40 UTC
