### ISSUE TITLE
Landscape orientation sensitivity issue 

### ISSUE THREAD

**Issue by Jacon6** [futo-org/grayjay-android#291] opened 2023-11-12 20:29 UTC
It's most likely a known issue already, but will voice my concern just for the heck of it.
The landscape orientation is so sensitive, a slight tilt of the screen can send it into a frenzy where it can't decide on horizontal or vertical view mode, just flickering between them.
Dunno if it could be a problem with my phone, though I've never had this happening with any other app.
Thanks for an overall great application though!

**Comment by palmerbomber1** [comment] 2023-11-12 21:34
There is a setting where you can set the dead zone for rotation selection from 0 to 20 degrees. It definitely reduces the frenzy you are talking about

I have mine set at 20 and i personally feel that's still a little too small of a setting cause while laying in bed it will still rotate when I'm mostly horizontal but not perfect because of fatigue

**Comment by Jacon6** [comment] 2023-11-12 22:02
Oh, I didn't notice that setting. Thanks! 
Definitely cool to have it as an option. Will probably take some time to get used to the app in it's entirety.
After changing I did notice a difference, though it can still become very indecisive with which orientation to stick with.
Probably needs an even larger dead zone as you hint at

**Comment by xephos1one** [comment] 2023-11-14 15:14
Duplicate of #67

**Comment by usertoroot** [comment] 2024-08-19 14:17
Next version will just use the standard Android rotation it should be a more stable experience on a wider array of devices.

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:20
Closing since duplicate of #67

**Closed by Zvonimir-FUTO** 2024-09-22 20:20 UTC
Labels: Bug, Duplicate, UI
