### ISSUE TITLE
Accessibility Request - Playback Bar Upgrade

### ISSUE THREAD

**Issue by ShawnNogi** [futo-org/grayjay-android#272] opened 2023-11-11 06:46 UTC
Please make the playback bar have a bigger responsiveness area . fast forwarding and rewinding while dragging on playback bar does not appear too particularly easy compared to youtube or other apps and often requires multiple drags or initial clicks.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:33
Duplicate of #62.

**Closed by Zvonimir-FUTO** 2024-09-24 19:33 UTC
Labels: Duplicate, Enhancement, UI/UX
