### ISSUE TITLE
Doubled overlapping HUD/GUI on video issue

### ISSUE THREAD

**Issue by lolakuti** [futo-org/grayjay-android#1239] opened 2024-08-11 06:53 UTC
### What happened?

![Screenshot_20240811-121317](https://github.com/user-attachments/assets/88ed55cc-da33-4372-b3ee-ded013b02c03)

Device: Moto Edge 30
Android: 13

How to replicate Issue: as you can see the GUI gets doubled.
How to replicate the issue: if my screen gets rotated to upside-down potrait and then rotated to landscaped (either way) this double HUD forms on video playback only. And if rotated to portrait
![Screenshot_20240811-122116](https://github.com/user-attachments/assets/2c401dab-15bc-49da-b639-6d591a38f2a9)
The issue is still there.

Temporary Fix: if I rotate screen from potrait to landscaped to portrait again, the doubled HUD issue fixes itself.

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by TobiPeterG** [comment] 2024-08-20 23:04
I also have this issue

**Comment by b-risk** [comment] 2024-08-31 04:58
GJ seems to have been very unstable with the android auto rotate option since tbe beginning, I just turned it back on after being disabled for months and this happened almost immediately

**Comment by support-grayjay** [comment] 2024-10-29 19:42
Duplicate of #582.

**Closed by support-grayjay** 2024-10-29 19:42 UTC
Labels: Bug, Duplicate, UI/UX, Core
