### ISSUE TITLE
Download list is unsorted

### ISSUE THREAD

**Issue by irinelturturea** [futo-org/grayjay-android#471] opened 2023-12-10 08:01 UTC
Hi
I would like a way to sort the download list or have it sorted with the last downloaded to the top.

**Comment by wolfkin** [comment] 2024-05-16 22:53
I'll cosign this. To repeat what I put in a downstream clone:

In my case I download a live stream from one of my political shows and luckily the streams, when I download them, have the date in the title but even with the date they're not in any order so it makes trying to find the oldest episode to watch kind of a task.

There are other shows I would download to watch later but they don't have date in title and the video date is soft relative ("3 months ago" and "1 year ago") which is less helpful with a program that puts out new videos 2-3 times a week.

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:57
Duplicate of #78

**Closed by Zvonimir-FUTO** 2024-09-22 20:57 UTC
Labels: Duplicate, Enhancement, UI
