### ISSUE TITLE
home recommendations page is short

### ISSUE THREAD

**Issue by Kchorus** [futo-org/grayjay-android#1195] opened 2024-07-28 13:25 UTC
### What happened?

On the home page, the recommendation feed is only about 20 videos long and it's always the same videos everytime but in a different order unless I individually hide each and every video manually.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

187

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by lmsalustri** [comment] 2024-07-28 16:35
Duplicate of #1059

**Closed** 2024-09-01 06:01 UTC
Labels: Youtube
