### ISSUE TITLE
Subscriptions only display while refreshing

### ISSUE THREAD

**Issue by DThomas44** [futo-org/grayjay-android#212] opened 2023-11-07 12:23 UTC
Phone:  Samsung Galaxy S9+
OS: Android 10
Kernel Version: 4.9.18
Grayjay Version Code: 190

Subscriptions feed is blank. When swiping down to refresh, previous results will show temporarily. When refresh completes, results disappear again leaving a blank page.

This is not the same as when the app intentionally displays a mostly blank page with a note about no results & instructs user to refresh. 

Issue has been persistent on my device for several releases. Have uninstalled & reinstalled several times as well as allowing the auto update to install the current version.

**Comment by DThomas44** [comment] 2023-11-07 12:32
Screen shot of the "blank" page i am seeing.
https://linksharing.samsungcloud.com/avrvaWQj52wm

**Comment by Kelvin-FUTO** [comment] 2023-11-07 20:16
I believe this should be fixed in 191 (release likely tomorrow). If it is not fixed afterwards, feel free to reopen this issue.

**Comment by ykuksenko** [comment] 2023-11-09 17:13
After updating to 191 my subscriptions disappeared. If I touch `Videos` button at the top to disable and again to enable they show up for under a second, then disappear. Browsing subscriptions is now impossible for me.

**Comment by Kelvin-FUTO** [comment] 2023-11-09 18:22
@DThomas44 @ykuksenko 
We can't reproduce it ourselves so ideally we find things to narrow it down.

In upcoming hotfix version 192 (within an hour) will be toggle "Fetch on tab opened". This can be used as a temporary workaround to at least get your cache to show without it disappearing. This is a temporary measure to at least make subscriptions work a little for you.

Do you have any additional info about the behavior. 
How many subscriptions do you have, do you see any popups/exceptions, etc.
It appears your cache is working fine, but live results are failing for some reason.

A subscriptions export would help the most.
If you are willing to provide an export, you can probably best send it in a PM to me in our FUTO Chat (https://chat.futo.org/)

**Comment by Kelvin-FUTO** [comment] 2023-11-09 19:04
An additional setting in 192 was added "Always reload from cache" this may also be a temporary setting. 
It will cause the subscription feed to always get its data from the cache after an update. 
Its not ideal, as it means it will not fetch new content when scrolling down (only the first page will update).

But again, a temporary measure to help you along for now.

**Comment by DThomas44** [comment] 2023-11-10 00:46
Auto update to 192 actually made the subscriptions tab always be completely blank, no videos showing before, during or after a refresh.

I uninstalled, then downloaded a fresh universal APK from the website & installed.

Everything is currently working as expected other than the Rumble plugin, but I'll add to a related issue for that.

**Comment by Kelvin-FUTO** [comment] 2023-11-10 17:22
Version 192 should not have changed any default behaviors, only if you changed the settings.

**Comment by Kelvin-FUTO** [comment] 2023-11-10 21:11
This might be fixed in 193 (v148 of YT plugin), related to channels returning no content for non-english youtube accounts.
I'm closing this until someone can confirm the new versions don't fix this. In which case I got some more questions lined up.

**Closed by Kelvin-FUTO** 2023-11-10 21:11 UTC
