### ISSUE TITLE
YouTube videos randomly freeze at 1 minute mark

### ISSUE THREAD

**Issue by treyus30** [futo-org/grayjay-android#1155] opened 2024-07-15 21:58 UTC
### What happened?

This has happened for a while, but usually like in one of the first 3 videos I watch in a day will freeze at the 1 minute mark and I have to fully close out of the video and reclick on it to get it to play past 1 minute. 

### Grayjay Version

249

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

185

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by lmsalustri** [comment] 2024-07-16 05:13
Duplicate of #1026

**Comment by treyus30** [comment] 2024-08-01 05:59
This seems to he resolved. I now get "YouTube blocking attempt (i) bypassed" at the beginning of some videos and I haven't gotten the 1min block since

**Closed** 2024-08-01 05:59 UTC
Labels: Youtube

**Comment by Rafael1712** [comment] 2024-08-01 10:09
> ### What happened?
> 
> This has happened for a while, but usually like in one of the first 3 videos I watch in a day will freeze at the 1 minute mark and I have to fully close out of the video and reclick on it to get it to play past 1 minute.

I have been experiencing this issue the past few hours, with the main differences being:

1. It applies to every video I have tried to watch.
2. Once the video reaches 1 minute, an error  message appears and the app goes through the bypasses again. The video starts playing from 0:00. Rinse and repeat.
3. The issue is not fixed after reloading the video or restarting the app.

Please consider reopening the issue, or tell me if it would be more appropriate for me to post this as its own issue. Thank you for your work.

**Comment by lmsalustri** [comment] 2024-08-01 15:06
@Rafael1712 someone already made your issue in #1188
