### ISSUE TITLE
[Feature Request] Enable switching from playing in the background to player overlay

### ISSUE THREAD

**Issue by leoncodev** [futo-org/grayjay-android#99] opened 2023-10-27 08:32 UTC
Hey, YouTube premium has this neat feature where you have a button on the player overlay that turns off the overlay and keeps the audio playing in the background, so you can switch between the two modes while playing a video without going into the settings.

**Comment by Zvonimir-FUTO** [comment] 2024-12-14 15:25
Duplicate of #181.

**Closed by Zvonimir-FUTO** 2024-12-14 15:25 UTC
Labels: Duplicate, Enhancement, UI/UX
