### ISSUE TITLE
Aggressive Autorotate

### ISSUE THREAD

**Issue by lolakuti** [futo-org/grayjay-android#1041] opened 2024-05-26 18:49 UTC
The auto rotate is very aggressive even after Disabling /setting as system(disabled) /setting Deadzone at max (20°)

The app is practically irritating when trying to watch lying down

Info:
Version - 242
Version Type - Release
Phone - Moto Edge 30
Android - 13

**Comment by dcalitri** [comment] 2024-05-27 19:03
I have the same issue too.

**Comment by dcalitri** [comment] 2024-05-27 19:04
It also leads to a double overlay of the video ui.

**Comment by xephos1one** [comment] 2024-05-29 16:17
Duplicate of #67

**Comment by KannaHayabusa** [comment] 2024-06-29 18:28
So glad that I paid for something the devs have not fixed for more than half a year!

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:25
Will be solved through #67

**Closed by Zvonimir-FUTO** 2024-09-22 20:25 UTC
Labels: Bug, Duplicate, UI
