### ISSUE TITLE
Entering fullscreen while the video is buffering leaves the application in portrait mode

### ISSUE THREAD

**Issue by edo9300** [futo-org/grayjay-android#1586] opened 2024-12-09 22:21 UTC
### What happened?

If you swipe up to enter fullscreen while the video is still loading for the first time, the player will go in fullscreen but the application will remain in portrait mode.
Running on an Asus zenfone Max pro m1 with arrow is 11

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by VoxelPrismatic** [comment] 2024-12-09 22:43
Can reproduce
Sony Xperia 1 V; Android 14

**Comment by Zvonimir-FUTO** [comment] 2024-12-10 08:05
Duplicate of #1571.

**Closed by Zvonimir-FUTO** 2024-12-10 08:05 UTC
Labels: Bug, Duplicate, UI/UX, Core
