### ISSUE TITLE
[Issue] video player video time

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#443] opened 2023-12-05 17:45 UTC
I realized the player stops playing the video about 1 seconds before the video end. I thought thats because the creator cut the video exactly that time. But seeing the speakers speech interrupted every time make me suspected. So am i reporting this

**Comment by xephos1one** [comment] 2023-12-06 18:20
Duplicate of #36

**Closed** 2024-06-19 21:42 UTC
