### ISSUE TITLE
it's not showing more videos 

### ISSUE THREAD

**Issue by Heroknight18** [futo-org/grayjay-android#1118] opened 2024-07-06 11:14 UTC
### What happened?

it ain't showing alot more videos 

### Grayjay Version

184

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Heroknight18** [comment] 2024-07-06 17:22
it's not loading more videos

**Comment by lmsalustri** [comment] 2024-07-20 19:43
Duplicate of #1059

**Comment by grayjay-support-FUTO** [comment] 2024-10-02 21:22
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Closed by grayjay-support-FUTO** 2024-10-02 21:22 UTC
Labels: Bug, Duplicate, Youtube
