### ISSUE TITLE
YouTube comments error

### ISSUE THREAD

**Issue by armilancode** [futo-org/grayjay-android#756] opened 2024-02-01 06:30 UTC
This error occurs when trying to read the platform comments, in this case, of YouTube:

![Screenshot_20240201_072906_Grayjay.png](https://github.com/futo-org/grayjay-android/assets/120649208/ac7de447-0947-4991-a2e0-6d7997bff484)

**Comment by xephos1one** [comment] 2024-02-02 08:46
I don't know how to replicate it.
It isn't fixed by Closing and reopening the video.
However it is fixed by closing and reopening the app.

**Comment by dimyself** [comment] 2024-02-03 07:33
i'm having this issue as well. It just started today for me.

This happens on every youtube video. Comments dont load for any of them.

Odysee comments are still working. It appears to be youtube specific, at least for me 

Latest version of the app and plugins

> I don't know how to replicate it. It isn't fixed by Closing and reopening the video. However it is fixed by closing and reopening the app.

Not in my case. I close and reopen app, click a video, same error.

**Comment by dimyself** [comment] 2024-02-03 07:50
> i'm having this issue as well. It just started today for me.
> 
> This happens on almost every youtube video I try. Comments dont load for most videos.
> 
> Odysee comments are still working. It appears to be youtube specific, at least for me
> 
> Latest version of the app and plugins
> 
> I can provide youtube links for working and non working videos if it will help...
> 
> > I don't know how to replicate it. It isn't fixed by Closing and reopening the video. However it is fixed by closing and reopening the app.
> 
> Not in my case. I close and reopen app, click a video, same error.

I just fixed mine!

I went into youtube source plugin, and hit "reinstall"

Now it appears , all videos are loading comments now!

So, anyone having this issue might try to reinstall the youtube plugin in the Sources tab

**Comment by Kelvin-FUTO** [comment] 2024-02-05 18:19
This is an issue with Youtube sometimes responding with a new format that we haven't implemented yet.
Since Youtube does staged rollout of these things, sometimes only affecting a fraction of the user base its often hard to reproduce. I've seen this in my app as well, and we can likely fix it structurally soon as it appears more often.

**Comment by Kelvin-FUTO** [comment] 2024-02-06 19:54
I pushed an update to the Youtube plugin (v166). You should be able to update to it from within Grayjay.

This adds support for this new comments model. From my testing, it seems they are A/B testing it 1/20 users sessions or so. But at least this should add support for it now.

**Closed by Kelvin-FUTO** 2024-02-06 19:54 UTC

**Comment by armilancode** [comment] 2024-04-04 09:57
> I pushed an update to the Youtube plugin (v166). You should be able to update to it from within Grayjay.
> 
> This adds support for this new comments model. From my testing, it seems they are A/B testing it 1/20 users sessions or so. But at least this should add support for it now.

It is fixed for me , thank you
