### ISSUE TITLE
[Odysee] - Plugin stops buffering on certain videos

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#405] opened 2023-11-27 17:57 UTC
For instance this one https://odysee.com/tsp-235-stanford-research-sr650-dual#80effe002f4ca5b153f06e209fab60d4874d3e6d

It loads and plays circa until the 2 minutes mark, then stops and doesn't play. Can't even seek.

But this one is fine https://odysee.com/eevblog-1582-fnirsi-dpox180h-180mhz-dpo#530c690c329982b8afb2633f27e5f8e59874c7bb

See the following uploaded logs id:
![Screenshot_20231127-185558](https://github.com/futo-org/grayjay-android/assets/11365978/3554a8e4-643d-4410-b59d-d1b04755b35d)

**Comment by koen-futo** [comment] 2023-11-30 13:22
That is interesting, I can also reproduce it by trying to play the video in my browser using the URL https://player.odycdn.com/v6/streams/80effe002f4ca5b153f06e209fab60d4874d3e6d/26da31.mp4

Will look into this further

**Comment by teaalltr** [comment] 2023-11-30 16:16
@koen-futo https://odysee.com/Haiku-OS-Update#5165b6885fdd0ef46f5952689a32c949385c1ce3 this video also doesn't play, but from the start, not even the first 2 mins are played. Just sent logs, see `c6412fe3-df11-4f5d-b5ab-cc-679afbf18c`

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 17:33
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Closed by Zvonimir-FUTO** 2024-09-25 17:33 UTC
Labels: Bug, Odysee
