### ISSUE TITLE
[Feature Request] Improved Playlist Features

### ISSUE THREAD

**Issue by Gthbacc** [futo-org/grayjay-android#319] opened 2023-11-16 10:45 UTC
Before I start this request, I would like to thank all the developers working on this project. Gray Jay is truly a gem of an app with a lot of potential ahead of it. I have fully migrated from newpipe and would buy the app as soon as a crypto purchase option becomes available. Also if anything in this thread has previously been mentioned in a prior one, I apologize in advance. I dont intend to clutter the issues section.
Basically, I believe the playlists can be much more better if these changes where added:

**1. Syncable Playlists**: as you know, there are already playlists created and moderated by existing youtube channels. Right now, you can only import them to gray jay as local playlists that wont be updated if a creator decides to add a video to the mentioned playlist.
This can be achieved via a simple checkbox upon adding the playlists to grayjay, asking whether or not the app should "sync" the playlist everytime the app opens to add newer videos or not. If left unchecked, then they will be local playlists where one can add videos to them manualy.
Additionally, this can be useful upon adding entire channels as playlists as well. I personally dont intend to sub to every single channel and I rather reserve that for the ones I care about the most (blame it on my adhd lol). This way, one can keep a less cluttered home screen and keep up to date with certain channels.

**2. Favorite videos**: one can have hundreds of videos in a playlist, but some might be more important than others. The ability to "star" those videos in a playlist will separate them from the others.

**3. Gestures for removing or starring videos**: currently, there is a simple trashcan button to the right of every video which might cause accidental deletions. One could for example swipe left to star a video (on both local and syncable playlists) and swipe right to delete a video (on local playlists, preferably with a 5 second undo pop up).

**4. Sorting videos in playlists**: Alphabetically, by date added, by upload date, favorites, etc...

**5. Searchable playlists**: for searching content within a playlist.

Thank you for your hard work. I apologize if I sound demanding. My intention is for this app to be better. Good luck to you all.

**Comment by Gthbacc** [comment] 2023-11-27 16:52
Hey. Thought I'd share some new possible improvements I think will be good. Also shameless self bump lol.

6. Tags: ability to add custom made tags to videos for better search. For example, there are a bunch of videos reviewing the yamaha xsr155 with different creators and titles. Adding #XSR155 to each video will make it easier to search for. This maybe a bit overkill and useless though. Not too sure about this one. Maybe it would be better if it was used while searching videos across all playlists?

7. Sorting videos by the channel that uploaded them to the platform.

8. Locking playlists (to avoid deletion or changing the videos sort settings)

9. Multi select (useful for mass deletions, moving multiple videos to different playlists, etc...)

**Comment by benninkcorien** [comment] 2023-12-04 21:16
11. Export a playlist to CSV or JSON as a list of video URLs and titles/creators/duration/date
(So I can edit it and use it with yt-dlp on PC).

**Comment by Gthbacc** [comment] 2023-12-25 14:51
12. Sorting (the playlists themselves) by different factors (A-Z, Most Played, etc)

13. Playlist Groups (similar to the channels)

14. "Duplicate" video options: basically what newpipe does. Adding a button to remove duplicates from a playlist and also warning the user upon adding the video that this video already exists in the playlist.

If anybody else feels the need to add their opinions and recommendations regarding playlists, please post them here to avoid cluttering the issues section.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 20:19
Please open a separate feature request for each thing. Luckily for most of them someone already opened a feature request.

For example first issue is duplicate of #157.

**Closed by Zvonimir-FUTO** 2024-09-24 20:19 UTC
Labels: Duplicate, Enhancement, Playlists
