### ISSUE TITLE
Auto Rotate Setting Fix

### ISSUE THREAD

**Issue by SurrealWarfare** [futo-org/grayjay-android#798] opened 2024-02-12 23:34 UTC
As i try to rotate my device, the video will randomly go back to portrait mode. ( From landscape of course). Even when i disable my auto rotate on my device, this issue persists. I have already tried adjusting the auto rotate zone from 0 to 20, with no luck. 

Thank you guys for making this project i absolutely love it and would like to support the app, but before I can, i need a full replacement to YouTube.

**Comment by OkieNeck** [comment] 2024-05-14 23:19
Same issue. Any lateral bump or vibration and it rotates back and forth regardless of dead zone setting on my S24.

**Comment by RSXEnthusiast** [comment] 2024-08-13 15:50
> Duplicate of #67

This is not a duplicate of #67. #67 reffers to the deadzone setting not working and the app auto-rotating when the device is barely tilted.

I believe that this issue referrs to the issue that I'm having, the issue that occurs when auto-rotate is disabled, you're watching a video in fullscreen landscape, and when you tilt your device to portrait it goes to fullscreen portrait, even if the fullscreen portrait setting is disabled.

I have tried every combination of "auto rotate" "disabled/enabled/match device setting (with device setting enabled/disabled" and "portrait in fullscreen" "on/off," and deadzone (even though this should be irrelevant)

My reproduction steps:

1. Browse to and start watching a video, all in portrait mode.
2. Tap the fullscreen button in the video player.
    - Video should change to playing in fullscreen landscape.
3. Rotate device to landscape to match the video.
    - Note that landscape works as intended and auto-rotates as intended between the two opposing landscape views.
4. Rotate device to Portrait.
    - Note that application is stuck in this portrait mode bug state until you exit fullscreen.
    
I'll be trying a clean install of the app to see if the allow portrait fullscreen is in some sort of bug state, that's my best guess as to what's happening.

**Comment by RehmatSChawla** [comment] 2024-08-15 09:16
I have the same issue.

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:23
> > Duplicate of #67
> 
> This is not a duplicate of #67. #67 reffers to the deadzone setting not working and the app auto-rotating when the device is barely tilted.
> 
> I believe that this issue referrs to the issue that I'm having, the issue that occurs when auto-rotate is disabled, you're watching a video in fullscreen landscape, and when you tilt your device to portrait it goes to fullscreen portrait, even if the fullscreen portrait setting is disabled.
> 
> I have tried every combination of "auto rotate" "disabled/enabled/match device setting (with device setting enabled/disabled" and "portrait in fullscreen" "on/off," and deadzone (even though this should be irrelevant)
> 
> My reproduction steps:
> 
>     1. Browse to and start watching a video, all in portrait mode.
> 
>     2. Tap the fullscreen button in the video player.
>        
>        * Video should change to playing in fullscreen landscape.
> 
>     3. Rotate device to landscape to match the video.
>        
>        * Note that landscape works as intended and auto-rotates as intended between the two opposing landscape views.
> 
>     4. Rotate device to Portrait.
>        
>        * Note that application is stuck in this portrait mode bug state until you exit fullscreen.
> 
> 
> I'll be trying a clean install of the app to see if the allow portrait fullscreen is in some sort of bug state, that's my best guess as to what's happening.

Rotation issues are being solved through #67.

**Closed by Zvonimir-FUTO** 2024-09-22 20:23 UTC
Labels: Bug, Duplicate, UI
