### ISSUE TITLE
Video engine crashes after watching for a moment

### ISSUE THREAD

**Issue by JACHUPOL** [futo-org/grayjay-android#1101] opened 2024-06-28 18:20 UTC
![Screenshot_20240628-201710_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/44097279/a4680c46-b98e-4745-b758-41a7fd167380)

**Comment by JACHUPOL** [comment] 2024-06-28 18:22
Reloading either does nothing or starts the video from the beggining and it breaks again after a moment. I have already tried downgrading the yt extension and relogging.

**Comment by Warlock-tourist** [comment] 2024-06-28 21:53
Can confirm. Have the very same issue

**Comment by contactnat** [comment] 2024-06-29 10:24
Yup, me too

**Comment by Epo-chico** [comment] 2024-06-29 18:30
Me too I am running a samsung galaxy s24 ultra if that matters

**Comment by fernandopal** [comment] 2024-06-30 14:48
It crashes at around 1 minute, seems to happen with youtube videos only

**Comment by Epo-chico** [comment] 2024-06-30 19:09
Youtube videos only work if they are age restricted. Go ahead and watch a naked yoga video. It will play without issues. Otherwise it would crash after a minute

**Comment by samsquanch01** [comment] 2024-07-01 02:51
Mine all crash with that error as well, I tried dumping the logs but that button seems to be the only one that doesn't work.  Id  id gladly help however I can to figure these issues out

**Comment by contactnat** [comment] 2024-07-01 03:06
> Youtube videos only work if they are age restricted. Go ahead and watch a naked yoga video. It will play without issues. Otherwise it would crash after a minute

oh my, I did not know that was a thing haha, anyway I still get the error on those videos - viewing for research/testing purposes only of course..

**Comment by HaydenRuffo** [comment] 2024-07-03 17:16
Same issue here, about 27 seconds in

**Comment by fernandopal** [comment] 2024-07-04 22:21
I have recieved a new update for both, the youtube plugin and app and the issue persist

Uploaded logs forcing the crash: 8c613b1a-9bea-4dcd-8652-23f64fa3e5fb

**Comment by lmsalustri** [comment] 2024-07-07 15:23
Duplicate of #1026

**Comment by Bobertowns** [comment] 2024-07-10 20:14
If you log out of your account you can still watch things. But yeah you lose your feed

**Comment by contactnat** [comment] 2024-07-10 21:44
> If you log out of your account you can still watch things. But yeah you lose your feed

hope it gets resolved, Youtube/google finding ways to make it hard for services like this, there is talk of it on Reddit also. its made the app virtually unusable for me. 

[https://www.reddit.com/r/grayjay/comments/1dz7whn/youtube_wont_play_past_50_seconds/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)

**Comment by lmsalustri** [comment] 2024-07-10 22:43
@JACHUPOL, this issue is a duplicate. Please close it.

**Closed** 2024-07-10 22:58 UTC
