### ISSUE TITLE
[Freature Request] Sort Downloads

### ISSUE THREAD

**Issue by marurunk** [futo-org/grayjay-android#982] opened 2024-05-11 17:38 UTC
Will be more dynamic sort by date of the download, Alphabet, etc.
I have too many downloads 😸

**Comment by wolfkin** [comment] 2024-05-16 22:43
I've been meaning to make this request for months and apparently you beat me by 5 days. 

In my case I download a live stream from one of my political shows and luckily the shows when I download them have the date in the title but even with the date they're not in any order so it makes trying to find the oldest episode to watch kind of a task.

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:57
Duplicate of #78

**Closed by Zvonimir-FUTO** 2024-09-22 20:57 UTC
Labels: Duplicate, Enhancement, UI
