### ISSUE TITLE
Video list grid mixed thumbnails

### ISSUE THREAD

**Issue by i3130002** [futo-org/grayjay-android#1435] opened 2024-10-26 09:44 UTC
### What happened?

Love the idea and the work you're doing. 

I noticed that sometimes while I'm going through my feed, some of the videos are packed together and I'd like to share it with you.

I had to blur two of the videos in the screenshot:
![image](https://github.com/user-attachments/assets/3553e42c-6965-4720-a2fb-ad37cb2e245c)

This might have been fixed but just in case someone else experiences this issue they can add more information. 
To me it's just random and sometimes happens back to back.

`For the latest version at 27 September 2024 and before that.`

### Grayjay Version

Before 264

### What plugins are you seeing the problem on?

Youtube, Odysee, Rumble, PeerTube

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-11-18 12:47
Duplicate of #1469.

**Closed by Zvonimir-FUTO** 2024-11-18 12:47 UTC
Labels: Bug, Duplicate, UI/UX
