### ISSUE TITLE
[BUG] Video's cut a few seconds short at the end

### ISSUE THREAD

**Issue by GenericUsernameIsNotAvailable** [futo-org/grayjay-android#860] opened 2024-03-14 09:37 UTC
This has been a minor bug for some time, but only just has it actually impacted my experience.
It seems on almost all videos (at least on youtube plugin, may be applicable for other plugins- verification needed) the video, including audio, cuts a second or two short of the actual original video that may be viewed on the original source.

**Comment by xephos1one** [comment] 2024-03-21 12:04
Duplicate of #36

**Closed** 2024-04-08 16:03 UTC
