### ISSUE TITLE
[Feature Request] Add buttons or gestures to play the next and previous videos in the queue

### ISSUE THREAD

**Issue by anddns** [futo-org/grayjay-android#317] opened 2023-11-16 05:41 UTC
I've found the process of playing the next or previous video in a queue confusing and unintuitive. First, it's unintuitive because there are no user controls inside the video player itself to execute this task. Everything is done through the queue, found on the lower part of the screen. Second, it's confusing because the relation between the current video and the next video in the queue is ambiguous. Third, it's clunky because the user has to tap on the video inside this queue area to play the next video or tap the "View" button to extend the queue list and select a video.

With that being said, I would like to make a few suggestions to improve the user experience with the following features. 

a) Add buttons to play the next or previous video in a queue. Integrated these buttons directly into the video player, just like the play and pause buttons. 

b) Add gestures to play the next or previous video in a queue. Swiping to the left should play the next video, whereas swiping right should play the previous one.

c) Add gestures to play the first or last video in a queue. Swiping left or right, but holding the gesture for a moment, will trigger the playback of the first or last video in a queue.

I would like to thank everybody for this great project because now I can finally queue up some videos without having to pay a fortune. The ability to play videos in the background is also greatly appreciated.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 20:11
Duplicate of #120.

**Closed by Zvonimir-FUTO** 2024-09-24 20:11 UTC
Labels: Duplicate, Enhancement, UI/UX
