### ISSUE TITLE
Adding a video to playlist can add it multiple times

### ISSUE THREAD

**Issue by Shadouness** [futo-org/grayjay-android#379] opened 2023-11-23 05:01 UTC
Adding to playlist should allow only 1 instance of the same video.
Right now, a Playlist can have 10 videos, and it's possible that it's the same title. This should not be the case.

**Comment by Hammy0w0** [comment] 2023-11-27 02:58
I would like a pop-up warning you of of a duplicate video instead of an outright ban. I commonly 'sandwich' videos in my queue and would be sad if this feature disappeared.

**Comment by adam-devel** [comment] 2024-07-01 16:46
Duplicate of #305

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 20:00
Duplicate of #305.

**Closed by Zvonimir-FUTO** 2024-09-24 20:00 UTC
Labels: Bug, Duplicate, Playlists
