### ISSUE TITLE
[Feature Request] Improvements for Group select Creators

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#561] opened 2023-12-23 08:40 UTC
Having many platforms on grayjay means i have subscribed to "the same" channel sometimes 3-4 times on different platforms. 

When adding creators to a sub group i see the "same" channel 4 times without an indication of what platform. 
A quick improvement would beto make the sorting alphabetic or semi alphabetic so that channels with the same name will all appear together. 

A better longterm solution would be imo to allow some kind of manual or automatic linking of profiles like #244 or #560

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:07
Duplicate of #244.

**Closed by Zvonimir-FUTO** 2024-09-24 19:07 UTC
Labels: Duplicate, Enhancement, UI/UX, Polycentric
