### ISSUE TITLE
Video playback stops 1 second or 2 before the actual video

### ISSUE THREAD

**Issue by lflaurflorin** [futo-org/grayjay-android#1093] opened 2024-06-22 13:06 UTC
Hi. 
I've noticed that, at least for YouTube, at the end of every video,a second or two is truncated/missing. That is apparent especially when the person speaks and part of their last word is cut at playback end.

The playback shows like the whole video finished rendering (the replay button appears) but it doesn't contain the last second or 2 of content/sound) 

Version 242.

Thank you for the consideration in advance! 🙏

**Comment by xephos1one** [comment] 2024-06-26 05:49
Duplicate of #36

**Comment by SevastianGit** [comment] 2024-07-26 19:01
Please close, duplicate of #36

**Comment by lmsalustri** [comment] 2024-07-27 22:37
@lflaurflorin

**Comment by lflaurflorin** [comment] 2024-07-27 22:41
Sorry, i thought it was auto-closed - closing it from my end.

**Closed** 2024-07-27 22:40 UTC
