### ISSUE TITLE
Add share button at various places (Like channel banner, playlists)

### ISSUE THREAD

**Issue by MRDGH2821** [futo-org/grayjay-android#1252] opened 2024-08-19 18:08 UTC
### Use Cases

Just like there is a share button for individual videos, I would like to have share buttons at channel banner & playlists.

I'll mention other places where it is needed as and when I come to know.

If at all possible, one which doesn't feel like it would work is, sharing links to comment or just the comment text. ~~Can be overengineered to share entire comment thread.~~

### Proposal

The setting button or the 3 dot menu can show a share button which will allow us to share/copy link to channel/playlist.

### References

#519 #794 #634

**Comment by Zvonimir-FUTO** [comment] 2024-09-26 19:05
Duplicate of #519 and #634.

**Closed by Zvonimir-FUTO** 2024-09-26 19:05 UTC
Labels: Duplicate, Enhancement, UI/UX
