### ISSUE TITLE
Error: "Age restricted video; Youtube age restricted videos can be allowed using the plugin settings (358) [3-4]"

### ISSUE THREAD

**Issue by dimyself** [futo-org/grayjay-android#345] opened 2023-11-21 04:51 UTC
Hi there, this channel i'm subbed to I get this error when clicking on this video from today (his other videos all load fine)

I get this popup when i click on the videO:

Error: "Age restricted video; Youtube age restricted videos can be allowed using the plugin settings (358) [3-4]"

I checked in settings and dont see anyhthing about disabling age restriction?

I can load the video i get the error with fine in other players (like newpipe) without any errors and without having to login

I'm using the latest updated version of grayjay on GrapheneOS

Thank you!!

**Comment by koen-futo** [comment] 2023-11-21 19:27
Click on Source -> YouTube and then change the age restriction setting.

**Comment by dimyself** [comment] 2023-11-21 20:22
Thank you! I know I had set this before, I just couldnt find it!

I had this setting set before and something wiped the setting (maybe an
update)?

If i backup my settings (so they dont get overwritten each update) ... if i
need to restore the settings, will it overwrite my playlists, history,
subscriptions, etc?

Thank you!

**Comment by koen-futo** [comment] 2023-11-21 22:41
@dimyself It will not. Whenever you choose a backup to restore, you will be asked "Do you want to restore playlists" "Do you want to restore Y" etc. You can say yes or no to each.

**Comment by dimyself** [comment] 2023-12-04 23:52
> Click on Source -> YouTube and then change the age restriction setting.

Hi there, i'm having this issue (or similar) again.

This time when i click on the video (through youtube plugin), i get error:

"unavailable video; No sources found (384)[2-3]"

I already have "allow age restricted" checked on

I can open the same video and it plays through Newpipe

I see the error is different from my original post error. Are the errors listed in documentation anywhere? That way I can look them up as they occur.

I apologize if its just another setting i'm missing other than "allow age restricted"

Thank you!

**Comment by edo9300** [comment] 2024-06-27 15:08
This issue is still happening on grayjay 242 and YouTube plugin 182

**Comment by itsvrl** [comment] 2024-07-29 11:02
Still happens for me also in grayjay 242 and YouTube plugin 182

**Comment by dimyself** [comment] 2024-08-26 03:50
This just started happening with me again today. 

I do have "Allow age restricted" turned on

Last night i was playing a live stream fine.  

And today I try the same stream (and the channels other lives), and I get: 

"sign in to confirm age. Login required." then:

"failed to load video(scriptexception) plugin Youtube. Login requrired. Sign in to confirm age"

I am not logged into youtube.

I'm on the latest versions: Plugin version 192, Grayjay version 253

Thank you!

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 16:11
@dimyself Hey, this issue is a bit stale. Could you confirm if the issue is present to this day with the latest version of Grayjay.

**Comment by dimyself** [comment] 2024-09-25 17:32
> @dimyself Hey, this issue is a bit stale. Could you confirm if the issue is present to this day with the latest version of Grayjay.

Hey there, thanks for your reply... I think the popup was based on ip / vpn usage. It still comes up sometimes, but it is random. Since the latest update, it is much less frequent. 

One question I did have is... Does Youtube see my ip address when i watch a video through Grayjay? I think probably so since this login popup occurs based on ip?  

Should I close this issue?

Thank you!

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 17:40
> > @dimyself Hey, this issue is a bit stale. Could you confirm if the issue is present to this day with the latest version of Grayjay.
> 
> Hey there, thanks for your reply... I think the popup was based on ip / vpn usage. It still comes up sometimes, but it is random. Since the latest update, it is much less frequent.
> 
> One question I did have is... Does Youtube see my ip address when i watch a video through Grayjay? I think probably so since this login popup occurs based on ip?
> 
> Should I close this issue?
> 
> Thank you!

Glad to hear issue is resolved or at least less frequent. Youtube sees your IP address as nothing is routed through Grayjay server. 

Closing.

**Closed by Zvonimir-FUTO** 2024-09-25 17:40 UTC
Labels: Bug, Awaiting Info, Youtube

**Comment by dimyself** [comment] 2024-09-25 17:44
Thank you! I appreciate it!
