### ISSUE TITLE
[Bug] Videos start from beginning when changing connection

### ISSUE THREAD

**Issue by Derek-2000** [futo-org/grayjay-android#1657] opened 2024-12-24 15:44 UTC
### What happened?

videos crash and restart on changing from wifi to mobile connection

### Grayjay Version

278

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

219

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Are you using a VPN?

No

**Comment by Zvonimir-FUTO** [comment] 2024-12-27 19:48
Duplicate of #1665.

**Closed by Zvonimir-FUTO** 2024-12-27 19:48 UTC
Labels: Bug, Duplicate, Core
