### ISSUE TITLE
Purchase option is broken

### ISSUE THREAD

**Issue by dev-inside** [futo-org/grayjay-android#1594] opened 2024-12-11 09:17 UTC
### What happened?

Hey,
first of all, I love your work and I wanted to share my appreciation by purchasing a license  - like I did with the great FUTO-Keyboard <3

Anyway, when I try to purchase a license, I get the following error 

**_GERMAN Translation:_**
"The required payment data cannot be retrieved."
![purchase_bug](https://github.com/user-attachments/assets/191510bb-ea6b-47ae-b63c-cba52febd42e)

Also the "0.0.0.0:43" in the end look like a misconfiguration of some sort.

### Grayjay Version

268

### What plugins are you seeing the problem on?

Other

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-12-11 09:46
@dev-inside please update Grayjay to the latest version (v268) and see if the error occurs again.

**Comment by Zvonimir-FUTO** [comment] 2024-12-11 13:44
Will be fixed in the next release. You can also buy a license from our website: https://pay.futo.org/api/PaymentPortal

**Comment by Zvonimir-FUTO** [comment] 2024-12-14 10:51
This has been fixed in v276.

**Closed by Zvonimir-FUTO** 2024-12-14 10:51 UTC
Labels: Bug, Solved, Payment

**Comment by ClientIco** [comment] 2025-01-10 08:55
![image](https://github.com/user-attachments/assets/e2aba618-53a7-41db-bab2-46aa669475f3)


Got the license but won't work on desktop or even the android version

**Comment by ClientIco** [comment] 2025-01-10 09:18
I have uploaded from the android device the subscription list that seems to have an issue. Let me know what I need to give additionally

**Comment by ClientIco** [comment] 2025-01-10 09:27
Desktop just fails:

![image](https://github.com/user-attachments/assets/061384d8-adcc-4cce-9a4e-d2bde7bc3202)

**Comment by Zvonimir-FUTO** [comment] 2025-01-10 09:54
@ClientIco These don't seem related to license. Could you open new issues for these at the following links?

https://github.com/futo-org/Grayjay.Desktop/issues/ - for Desktop issue
https://github.com/futo-org/grayjay-android/issues/ - for Android issue

Also please provide more information so it is easier to troubleshoot and find where the issue is.
