### ISSUE TITLE
Please Remove Unnecessary White Bars On Top In Fullscreen

### ISSUE THREAD

**Issue by JasonCraft** [futo-org/grayjay-android#1510] opened 2024-11-23 01:27 UTC
### Use Cases

![20241123_032132](https://github.com/user-attachments/assets/9b408553-f928-4277-9b17-8b51a4d7b7e8)
As per attached and indicated in the image, these unnecessary bars in full-screen do nothing but contribute to screen burn-in.

### Proposal

Please remove the bars, as they serve no purpose but harm screen longevity.

**Comment by Zvonimir-FUTO** [comment] 2024-11-23 07:53
Duplicate of #315.

**Closed by Zvonimir-FUTO** 2024-11-23 07:53 UTC
Labels: Bug, Duplicate, UI/UX, Core
