### ISSUE TITLE
ability to save the que as a playlist.

### ISSUE THREAD

**Issue by jmcgaughey** [futo-org/grayjay-android#1325] opened 2024-09-10 17:12 UTC
### Use Cases

when i have a que that has a long list of videos to watch if we can save the que as a playlist or the videos in the que have an option under each video to save to playlist.

### Proposal

have the same options for the videos in the que that the videos in the home/search tabs have as in save to playlist/watch later, download, etc

**Comment by support-grayjay** [comment] 2024-11-03 11:20
Duplicate of #881.

**Closed by support-grayjay** 2024-11-03 11:20 UTC
Labels: Duplicate, Enhancement, UI/UX, Playlists, Core
