### ISSUE TITLE
FEATURE: Ability to close the PIP window 

### ISSUE THREAD

**Issue by sigboe** [futo-org/grayjay-android#529] opened 2023-12-19 18:06 UTC
YouTube's PIP window has a headset icon, pressing that closes the PIP window, this is useful when using the phone while playing a video that is totally suitable for just listening. When you want the PIP window back you just open the app and background it again to get the PIP window.

This is better than just pushing the PIP window to the side, since it doesn't cover any part of the screen anymore and it conservs battery as well. And it is easier for the phone if you have a heat wave, or it's hot in the car.

Please I miss this feature.

**Comment by koen-futo** [comment] 2023-12-20 10:03
We will add it

**Comment by birdup000** [comment] 2023-12-20 16:38
#181 like this...

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 18:19
Closing as duplicate of #181.

**Closed by Zvonimir-FUTO** 2024-09-24 18:19 UTC
Labels: Duplicate, Enhancement, UI/UX
