### ISSUE TITLE
Password confirmation/unhide for auto backup

### ISSUE THREAD

**Issue by FraYoshi** [futo-org/grayjay-android#1056] opened 2024-06-04 19:07 UTC
When setting up an automatic external backup, the user is prompted for a password but there is no confirmation nor an un-hide option, so the user cannot really be sure if they mistyped it.

Proposed solution:
- un-hide pass
- confirm pass
- both
- both, but if un-hide is pressed, confirmation is not needed.

**Comment by grayjay-support-FUTO** [comment] 2024-10-02 21:02
Duplicate of #210.

**Closed by grayjay-support-FUTO** 2024-10-02 21:02 UTC
Labels: Duplicate, Enhancement, UI/UX, Backup
