### ISSUE TITLE
YT: fail to download video: Retrieved wrong segment

### ISSUE THREAD

**Issue by secretmango** [futo-org/grayjay-android#1405] opened 2024-10-15 21:34 UTC
### What happened?

GrapheneOS, Android 14

Since a few days, video download doesnt work anymore. 

Errror: 

Retrieved wrong segment: 0 != 4 (2126) [3-4]

These numbers are always different

Using sponsorblock enabled and login as fallback

![Screenshot_20241015-232927](https://github.com/user-attachments/assets/9d4eb297-a30a-44fc-b83f-b599e880cca6)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by DerangedWifi** [comment] 2024-10-17 05:23
I'm also having this issue.

**Comment by MFry** [comment] 2024-10-17 12:38
I have been encountering this issue as well. It might be caused by the size of the video? ~2.5 hours, and it's a members only video

**Comment by Kelvin-FUTO** [comment] 2024-10-22 02:36
This issue should have been fixed with a Youtube plugin update from last week.

If encountered on latest versions, please reopen.

**Closed by Kelvin-FUTO** 2024-10-22 02:36 UTC
Labels: Bug, Youtube, Downloads
