### ISSUE TITLE
Syncing playlists with YouTube account

### ISSUE THREAD

**Issue by BirchBranch2121** [futo-org/grayjay-android#253] opened 2023-11-10 06:23 UTC
I primarily use this app for getting around those few videos that won't let you watch them in embedded mode and for playlists, which would otherwise have ads in between songs.

When I add a song or video to a playlist on my computer, I want the playlist on grayjay to be updated, either automatically or manually. Currently I don't see a way to do that without signing in and out frequently. Having a "sync playlists" or "update playlists" button that somehow gets new additions to the playlists would be great.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:19
Duplicate of #157.

**Closed by Zvonimir-FUTO** 2024-09-24 19:19 UTC
Labels: Duplicate, Enhancement, Playlists
