### ISSUE TITLE
not showing any playlists

### ISSUE THREAD

**Issue by Heroknight18** [futo-org/grayjay-android#1483] opened 2024-11-15 17:54 UTC
### What happened?

it's not showing any playlists when i use it

### Grayjay Version

212

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-11-15 18:22
Duplicate of #1467.

**Closed by Zvonimir-FUTO** 2024-11-15 18:22 UTC
Labels: Bug, Duplicate, Youtube, Playlists
