### ISSUE TITLE
GrayJay starts randomly playing a stopped video in the background.

### ISSUE THREAD

**Issue by bananabreadpineapple** [futo-org/grayjay-android#398] opened 2023-11-26 11:32 UTC
It happens in my pocket, or when I use my phone.

**Comment by mnbvasd** [comment] 2023-11-29 11:44
I think this maybe related to #409 and #338.

I experience this too.

It also sometimes randomly starts playing when paused. I have terrible wifi that always drops out.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 16:06
Duplicate of #338.

**Closed by Zvonimir-FUTO** 2024-09-25 16:06 UTC
Labels: Bug, Duplicate, UI/UX
