### ISSUE TITLE
Rumble channels empty

### ISSUE THREAD

**Issue by aintisaword0** [futo-org/grayjay-android#531] opened 2023-12-19 19:06 UTC
When trying to directly access the channel of a Creator on Rumble the channel is completely blank. Once I try to go directly to their Channel I also find that the icon in my subscription box goes black. This has happened for multiple subscriptions and I've had to switch to their YouTube channels.

**Comment by JDog2pt0** [comment] 2023-12-19 23:26
Duplicate of #507

**Comment by koen-futo** [comment] 2023-12-20 11:01
Fixed in next build.

**Closed by koen-futo** 2023-12-20 11:01 UTC
