### ISSUE TITLE
[Feature Request] Add DeArrow support to Youtube plugin

### ISSUE THREAD

**Issue by s8alvi** [futo-org/grayjay-android#872] opened 2024-03-23 08:23 UTC
Make it possible that Graygay users can add their own, more suiting, title to a video and display it to others, others vote if that title is better. Or implement an AI that helps do that. Make this feature easy to put on and off, maybe just by clicking on original title. Something similar for a video description too.

**Comment by Tsunami014** [comment] 2024-03-25 07:07
Like [this?](https://dearrow.ajay.app/) (I think made by the same people who did the sponsorblock that is a feature in the Youtube plugin)

**Comment by Zvonimir-FUTO** [comment] 2024-11-11 17:47
Duplicate of #307.

**Closed by Zvonimir-FUTO** 2024-11-11 17:47 UTC
Labels: Duplicate, Enhancement, UI/UX, Low Priority, Youtube
