### ISSUE TITLE
YouTube home feed and video playback broken

### ISSUE THREAD

**Issue by shadoxxhd** [futo-org/grayjay-android#431] opened 2023-12-01 21:18 UTC
The YouTube home feed doesn't show any videos (screenshot 1), and trying to play a video from subscriptions shows an error message (screenshot 2).
![screenshot 1](https://github.com/futo-org/grayjay-android/assets/6153557/4378385e-8649-4902-af61-78cc7e819306)
![screenshot 2](https://github.com/futo-org/grayjay-android/assets/6153557/3f8a00d1-56c9-47d6-b730-12ff4af7e64f)

This issue is intermittent - after 1-2 days, everything is working again, but a couple days later the issue reoccurs.

**Comment by shadoxxhd** [comment] 2023-12-02 00:46
I just installed grayjay on another device - before logging into YouTube, the home feed showed videos, but after logging in with the same account as on my phone, the same issue appeared.
So this does look like some sort of A/B test...
Do you need some kind of debug log from me, so you can see what causes the issue?

**Comment by shadoxxhd** [comment] 2023-12-02 00:54
Actually, the issue only seems to occur on a certain "channel" associated with the account, and doesn't occur with the other channel on the same account.

**Comment by shadoxxhd** [comment] 2023-12-04 05:33
Since my last comment, the issue has been present for me whenever I tried to use Grayjay. What info do you need to tackle this problem?

**Comment by shadoxxhd** [comment] 2023-12-05 00:26
Yes, one account that has multiple channels, and one breaks Grayjay while the other doesn't.

The channel that causes the issue is the one I use regularly; the other is an old one (not in normal use for years), and has a few videos/subscribers associated with it. The account was recently (few months ago) on a premium trial that was canceled before first payment. Other than that, the account is used to access YouTube with different combinations of DNS level and/or browser level AdBlock (depending on device), so if the theories that YouTube illegally collects that info are actually true, my account/channel could be "flagged" in some way.

Interestingly, just now Grayjay started working again on my regular channel (first try since 18 hours ago). So I might not be able to provide log files until it starts happening again (probably in 1-3 days).

**Comment by Kelvin-FUTO** [comment] 2023-12-05 12:17
Weird thing is that unless you enable the toggles I mentioned before (use login for details/channels), we do not actually use your account to make any requests.
It should only affect home feed by default.
So that confuses me a bit.
I do intend to try a trial myself soon to support some of those features, so maybe I can reproduce it then.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 18:46
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Closed by Zvonimir-FUTO** 2024-09-25 18:46 UTC
Labels: Bug, Youtube
