### ISSUE TITLE
Gesture regions misaligned with screen

### ISSUE THREAD

**Issue by kiefac** [futo-org/grayjay-android#440] opened 2023-12-04 15:39 UTC
The width of the regions where gestures activate seem to be calculated based on the width of the whole screen, but are aligned with the left edge of the video. This is especially noticeable when trying to swipe down to exit fullscreen on a 4:3 video - you have to swipe on the right edge of the video, instead of directly in the middle; swiping in the middle lowers the brightness.

**Comment by xephos1one** [comment] 2023-12-04 16:02
Possibly a duplicate of #387

**Comment by koen-futo** [comment] 2023-12-04 19:12
Fixed in the upcoming update.

**Closed by koen-futo** 2023-12-04 19:12 UTC
