### ISSUE TITLE
[bug] Like button can go negative

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#843] opened 2024-03-06 11:22 UTC
![Screenshot_20240306-121959](https://github.com/futo-org/grayjay-android/assets/11365978/d8f6de8b-51a7-49dc-82a3-4c499185a49d)

Clicking it it goes to 0, instead of going from 0 to 1

**Comment by xephos1one** [comment] 2024-03-11 12:28
Possible duplicate of #388

**Comment by golgothan666** [comment] 2024-06-08 08:35
constantly happening to me, but seems to be playlist specific... as in, i like or dislike one video in a playlist (or even history, it seems), and all videos receive the same mark... i think it's been happening for several months now, but wasn't always the case

**Comment by golgothan666** [comment] 2024-06-08 08:40
> Possible duplicate of #388

there was a response to that, stating that platform vs Poly video ratings don't intermingle... so seemingly separate issues



quoted from #388:


xephos1one commented on Nov 25, 2023
Possibly related to #333

Kelvin-FUTO commented on Nov 27, 2023
Possibly related to #333

Platform ratings and Polycentric comments/ratings are seperate systems and thus shouldn't be related

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 20:32
Duplicate of #333.

**Closed by Zvonimir-FUTO** 2024-09-24 20:32 UTC
Labels: Bug, Duplicate, UI/UX, Youtube
