### ISSUE TITLE
Cannot export specific video to downloads

### ISSUE THREAD

**Issue by RORY1230** [futo-org/grayjay-android#1495] opened 2024-11-20 02:04 UTC
### What happened?

My device is an unrooted AT&T Samsung Galaxy Note 9 running the latest version of Android 10 that it supports. The YouTube plugin version is the latest one that I just installed, version 213.

Hopefully these steps can help recreate the bug to fix it. 
1. I pasted this link into the search bar on Grayjay:
https://www.youtube.com/watch?v=93ntopzqz4s

2. I downloaded the video for offline viewing.

3. I then went to my downloaded videos in Grayjay and tried to export it to my download folder on my phone.

The offline viewing seems to work fine through Grayjay, but whenever I try to export it to my downloads folder it just spins forever at 0% and never actually exports to my downloads forcing me to force close the app in order to get out of the exporting content screen and be able to use the app again. I've done it with 5 other videos the exact same way and they all exported to my downloads folder perfectly fine. Any help is appreciated. 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

213

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-11-20 16:51
Couldn't reproduce this. When you got to App Info (Grayjay), inside device settings and open Storage, can you clear access for external storage, maybe create a new folder to download to and try that?

**Comment by RORY1230** [comment] 2024-11-20 17:29
Thank you for the suggestion. I should have mentioned that I did already
try clearing Grayjay's access to external storage and giving Grayjay access
to the download folder again and also tried clearing the cache and storage
of Grayjay but nothing worked until just now. I didn't think to create a
separate download folder and that seems to have done the trick. I'm not
sure what was wrong with my downloads folder for just that one video. I
really appreciate the help.

**Comment by Zvonimir-FUTO** [comment] 2024-11-20 17:57
Thank you for the feedback. I'm not sure either why that solved it, I just know my phone blocks me from using Downloads so I had to create a new folder inside it anyway :)

Closing as solved.

**Closed by Zvonimir-FUTO** 2024-11-20 17:57 UTC
Labels: Bug, Youtube, Downloads, Core
