### ISSUE TITLE
Increase playback speed when holding screen

### ISSUE THREAD

**Issue by AndrewG2** [futo-org/grayjay-android#1471] opened 2024-11-12 05:24 UTC
### Use Cases

YouTube has a feature where you can touch and hold the phone screen right side of the playing video to increase playback speed at 2x, only while holding the screen then it returns to normal playback speed.  

### Proposal

Add touch and hold to temporarily increase video playback speed

**Comment by MKBontwikkeling** [comment] 2024-11-15 10:51
MERGE WITH:

https://github.com/futo-org/grayjay-android/issues/1369
"Hold down on video player to play video in 2x speed"

**Comment by Zvonimir-FUTO** [comment] 2024-11-15 13:56
Duplicate of #1369.

**Closed by Zvonimir-FUTO** 2024-11-15 13:56 UTC
Labels: Duplicate, Enhancement, UI/UX, Low Priority, Core
