### ISSUE TITLE
[Bug] [Nebula Plugin] Cannot download videos to offline: 404

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1587] opened 2024-12-09 22:52 UTC
### What happened?

Possibly due to however Nebula works, I cannot download videos.
I am happy to share an account for testing.

See the video below for steps

https://github.com/user-attachments/assets/1f58a755-eaa0-4580-bc18-74b6c4546e27

1. Click "Download" on a Nebula video
2. Click on HLS, because that's the only option
3. Download any video/audio combination
4. Fails: 404

### Grayjay Version

268

### What plugins are you seeing the problem on?

Nebula

### Plugin Version

11

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [X] N/A

**Comment by TheColorman** [comment] 2024-12-10 01:20
Duplicate of #1075

**Closed** 2024-12-10 04:41 UTC
