### ISSUE TITLE
Rumble plugin causes creator search to error out

### ISSUE THREAD

**Issue by jonathancutting** [futo-org/grayjay-android#1410] opened 2024-10-16 21:11 UTC
### What happened?

When the Rumble plugin is enabled, searching for creators on any platform errors out, and completing the search is not possible.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

45

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by jonathancutting** [comment] 2024-10-16 21:12
![Screenshot_20241016-170524](https://github.com/user-attachments/assets/d2000af2-6173-4c2a-8776-1791b5cb72a2)

**Comment by support-grayjay** [comment] 2024-10-28 17:26
I was not able to reproduce this. Could you please elaborate on "searching for creators on any platform"? Are you searching on Creators page?

**Comment by jonathancutting** [comment] 2024-10-28 18:59
Yes, when searching for creators on the Creators page using the magnifying glass in the top-right corner of the screen, that error will pop up if the Rumble plugin is enabled. Tapping "retry" will just cause the error to appear again after less than a second. Tapping "close" will cancel the search to allow use of the app again (albeit minus the creator I was looking for). GrayJay won't search the other platforms (e.g., YouTube, Odyssee, etc.) when Rumble causes this error. This was happening with every creator search for over a month, but it seems to be intermittent now. Some days, I can search without issue. Other days, I get this error. I haven't found a pattern to which are the error or error-free days.

**Comment by support-grayjay** [comment] 2024-10-28 19:35
Thank you for the clarification. I wasn't able to reproduce this immediately but I will try to reproduce it in the following days so please give me some time.

**Comment by Zvonimir-FUTO** [comment] 2024-11-18 11:43
Unfortunately I couldn't reproduce this.

**Comment by rhubear25** [comment] 2024-11-21 16:21
> Thank you for the clarification. I wasn't able to reproduce this immediately but I will try to reproduce it in the following days so please give me some time.

I CAN reproduce this.... 
SAME error, same way to reproduce.

In fact, rather than post my own error, I searched for duplicates, found this thread.

My Screenshot....

![Screenshot_20241121-164932](https://github.com/user-attachments/assets/5969244d-266a-45ab-bb11-156076f35c8c)

**Comment by kaidelorenzo** [comment] 2024-12-05 19:50
Version 46 has a fix for this issue

**Closed by kaidelorenzo** 2024-12-05 19:50 UTC
Labels: Bug, Rumble
