### ISSUE TITLE
Galaxy Fold: Larger Opened Screen View cuts off tops of videos [Screenshot Attached]

### ISSUE THREAD

**Issue by BrotherPanan** [futo-org/grayjay-android#204] opened 2023-11-07 01:54 UTC
Galaxy ZFold 5
App Version 190

When I watch videos with my ZFold5 opened to the larger screen, the tops of videos are all cut off.

![Screenshot_20231106_205006_Grayjay](https://github.com/futo-org/grayjay-android/assets/63543627/3695db4c-2875-496a-99af-4737da71415b)

**Comment by TheUbMunster** [comment] 2024-05-02 08:06
I have the same issue on my galaxy fold 3.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 18:40
Duplicate of #34.

**Closed by Zvonimir-FUTO** 2024-09-24 18:40 UTC
Labels: Bug, Duplicate, UI/UX, Edge Case
