### ISSUE TITLE
Automatically hide watched videos from home tab

### ISSUE THREAD

**Issue by jacobalvarez** [futo-org/grayjay-android#1176] opened 2024-07-22 12:47 UTC
### Use Cases

My home tab is cluttered mostly with videos I've already watched. I know about the Hide from Home button, but that's extremely tedious to use on every video I've watched. This renders the Home tab pretty much useless.

### Proposal

Could y'all make an option to automatically hide watched videos on the Home tab?

**Comment by Philippe-Choquette** [comment] 2024-08-23 16:43
Duplicate of #514

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 20:12
Duplicate of #189.

**Closed by Zvonimir-FUTO** 2024-09-25 20:12 UTC
Labels: Duplicate, Enhancement, UI/UX
