### ISSUE TITLE
Is there a way to disable auto-play (auto resume play) when switching networks? If not, I'd like to request this...

### ISSUE THREAD

**Issue by dimyself** [futo-org/grayjay-android#409] opened 2023-11-28 03:44 UTC
Everytime I change networks or switch from wifi <-> data, grayjay just starts playing no matter what i'm doing or what app I'm in. It is quite annoying

I've looked in settings and searched in issues, and dont see anything about auto play or resume play

Is there a settings I'm missing on this? If not, please add a settings to disable this

I'm on a pixel 6, graphene OS. Latest Grayjay update. Plugins just youtube and rumble.

Thank you!

**Comment by xephos1one** [comment] 2023-11-28 08:04
Related to #338

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 16:06
Duplicate of #338.

**Closed by Zvonimir-FUTO** 2024-09-25 16:06 UTC
Labels: Bug, Duplicate, UI/UX
