### ISSUE TITLE
Auto rotation too sensitive

### ISSUE THREAD

**Issue by remcomeeder** [futo-org/grayjay-android#892] opened 2024-04-02 20:33 UTC
On both my old phone (Huawei Mate 20 Pro) and my current Pixel 8 Pro the autorotation feature is way to sensitive. The dead zone doesn't seem to do anything.
It should behave the same as other apps behave when switching from portrait to landscape and vice versa.

**Comment by Legendary-Ra** [comment] 2024-04-04 02:06
I have this problem on my WP18, when I put the phone down horizontal it flips madly between full screen and portrait mode

**Comment by xephos1one** [comment] 2024-04-04 13:20
Duplicate of #67

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:24
Will be solved through #67

**Closed by Zvonimir-FUTO** 2024-09-22 20:24 UTC
Labels: Bug, Duplicate, UI
