### ISSUE TITLE
Option to save current queue as playlist

### ISSUE THREAD

**Issue by Auster-1** [futo-org/grayjay-android#1287] opened 2024-09-03 13:02 UTC
### Use Cases

When making a queue to watch, the user may not be able to watch it all in one go. In such cases, maybe have an option to save the whole queue as a new playlist so the playlist isn't lost, nor for the user to have to save each video/audio manually.

### Proposal

In Grayjay's player, besides the current 4 queue-related buttons, "Clear", "Shuffle", "Repeat" and "View", to have a 5th one, "Save...", which would let the user save the current queue as a playlist.

**Comment by support-grayjay** [comment] 2024-11-03 11:19
Duplicate of #881.

**Closed by support-grayjay** 2024-11-03 11:19 UTC
Labels: Duplicate, Enhancement, UI/UX, Low Priority, Core
