### ISSUE TITLE
Rotation lock does not work 

### ISSUE THREAD

**Issue by Flatmotion1** [futo-org/grayjay-android#1291] opened 2024-09-04 13:47 UTC
### What happened?

Since the new update to 259 rotation lock doesn't work anymore regardless of the settings. Video will now always rotate in full screen regardless of device level rotation lock or app level rotation lock. 

### Grayjay Version

259

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

195

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by WmeLuna** [comment] 2024-09-04 14:35
for me it respects the fullscreen rotation lock
but it now will rotate so its portrait and flipped portrait, which has been way more annoying

**Comment by Flatmotion1** [comment] 2024-09-04 14:53
Sorry I should've reworded it, that's what I mean.
It is full screen, but now, regardless of the lock settings that are on the top right of the screen, it'll rotate. Also disabling it in the app settings or phone system settings doesn't seem to influence this. It just keeps rotating.
![signal-2024-09-04-075148_003](https://github.com/user-attachments/assets/b44709bf-d216-4e80-afcd-1a6f24cd4e34)
![signal-2024-09-04-075148_002](https://github.com/user-attachments/assets/e08d4eb5-07ef-41de-932c-df0018557f96)

**Comment by usertoroot** [comment] 2024-09-05 07:43
Hmm am I correct in understanding that the issue is:
1. You are watching a video in portrait mode
2. You have auto rotate disable using the lock on the screen OR you have it disabled in settings
3. Whenever you rotate the device it will go between portrait and portrait flipped ?

**Comment by usertoroot** [comment] 2024-09-05 08:54
Proposed fix is out, hopefully release today or tomorrow.

**Comment by JustCryen** [comment] 2024-09-06 12:03
This has been fixed with the recent update, thank you!

**Comment by Kelvin-FUTO** [comment] 2024-09-06 17:57
Fix should be deployed (v261)

**Closed by Kelvin-FUTO** 2024-09-06 17:57 UTC
Labels: Youtube
