### ISSUE TITLE
Larger rotate deadzones

### ISSUE THREAD

**Issue by Roman19S** [futo-org/grayjay-android#1282] opened 2024-09-01 15:14 UTC
### Use Cases

I find that I tend to shift a lot while watching videos and rotating the screen when I don't intend to, but I hate the inconvenience if manual rotation.

### Proposal

Can you add larger deadzones like a 30 degree or 40 degree?

**Comment by xephos1one** [comment] 2024-09-02 13:30
Duplicate of #67 
Should be fixed in the upcoming version

**Comment by Zvonimir-FUTO** [comment] 2024-09-22 20:28
Will be solved through #67

**Closed by Zvonimir-FUTO** 2024-09-22 20:28 UTC
Labels: Bug, Duplicate
