### ISSUE TITLE
Skipping video portions it shouldn't

### ISSUE THREAD

**Issue by codyhood321** [futo-org/grayjay-android#1482] opened 2024-11-14 13:50 UTC
### What happened?

I'm watching a Fully Ramblomatic video and it skipped immediately past the intro, and after a second, skipped again over "filler." I backed the video up and it immediately skipped again. I double checked my YouTube plugin and both those skip options are disabled.

The video this occured on:
https://www.youtube.com/watch?v=18SbeaoMLJM

Screenshots with the notifications stating the skip occurring with the relevant settings visible.
![Screenshot_20241114_053839_Grayjay](https://github.com/user-attachments/assets/a6d9a876-bf55-48ad-96da-2d8b5abf6192)
![Screenshot_20241114_053846_Grayjay](https://github.com/user-attachments/assets/c5a8d7dd-a11f-44a6-b9e1-69bd1c053820)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

211

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment] 2024-11-14 15:48
Couldn't reproduce this. Could you try setting them all to manual for example and then back to no skip? 
Also, were they set to no skip previously or did you change them after the update?

**Comment by codyhood321** [comment] 2024-11-14 16:21
> Couldn't reproduce this. Could you try setting them all to manual for example and then back to no skip?

I full closed the app, restarted it, and didn't experience it again when starting the video again. However I do have sponsor skip enabled and there was a self promotion it skipped at the end of the video, could be related.

> Also, were they set to no skip previously or did you change them after the update?

They have always been set to no skip.

**Comment by WildFyr16** [comment] 2024-11-14 19:16
I am also having this issue, it only started after the latest YouTube plugin update. Typically I don't like skipping parts in videos unless it is a specific scam sponsor, or something I would never interact with like mobile games.
It seems like something in the latest update no longer checks what the status is in the settings before skipping

**Comment by Zvonimir-FUTO** [comment] 2024-11-14 20:42
We are looking into this. Thank you guys for the feedback.

**Comment by Zvonimir-FUTO** [comment] 2024-11-14 21:23
Released a hotfix in 212 to fix this issue so it should be fixed. I retested it and should be fine now but let us know.

**Comment by Zvonimir-FUTO** [comment] 2024-11-14 21:40
Closing issue, if you are still encountering it feel free to reopen or open a new one.

**Closed by Zvonimir-FUTO** 2024-11-14 21:40 UTC
Labels: Bug, Youtube, SponsorBlock
