### ISSUE TITLE
Add toggle to skip silence

### ISSUE THREAD

**Issue by lu4p** [futo-org/grayjay-android#1357] opened 2024-09-25 04:58 UTC
### Use Cases

If a user is mostly interested in listening to a video instead of watching, they could cut down the time it takes to watch a video by skipping silent parts.

The nice thing about this is that it doesn't hurt comprehension that much. So after a user found a playback speed they're comfortable with, they can cut down the time it takes to watch a video further.

### Proposal

Add a toggle under playback speed in the player called "Skip silence". 

If "Skip silence" is active the player should skip silent parts of a video, "parts" can be a small as just a couple frames.

Libretube and Newpipe have this.

**Comment by Zvonimir-FUTO** [comment] 2024-09-25 17:17
Duplicate of #864.

**Closed by Zvonimir-FUTO** 2024-09-25 17:17 UTC
Labels: Duplicate, Enhancement, UI/UX
