### ISSUE TITLE
youtube - captcha required

### ISSUE THREAD

**Issue by 584F525F** [futo-org/grayjay-android#917] opened 2024-04-19 22:13 UTC
2 days ago when playing videos i started getting a captcha required when trying to play a video.

If i do it, it will redirect me to yt in browser. If not i get an error 

failed to load video (scriptexception)  plugin [youtube]
[youtube] captcha required 
source.getContentDetails(...)

![IMG_20240419_181136.jpg](https://github.com/futo-org/grayjay-android/assets/161089469/4a70ac4a-6e8d-4147-a815-30a5764a5f15)

**Comment by Ser-Bul** [comment] 2024-05-10 22:18
Hi there, I experienced the same till one of the last updates of the Youtube plugin. If the issue is gone for you too - I advise closing the issue.

**Closed** 2024-05-22 02:59 UTC
