### ISSUE TITLE
Feature Request: Download All "Watch Later"

### ISSUE THREAD

**Issue by paperfairy** [futo-org/grayjay-android#302] opened 2023-11-13 21:55 UTC
On regular playlsits, there is a button that allows users to download all the videos on a playlist. This issue is to request this same functionality for the "Watch Later" list.

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 19:55
Duplicate of #116.

**Closed by Zvonimir-FUTO** 2024-09-24 19:55 UTC
Labels: Duplicate, Enhancement, Playlists, Downloads

**Comment by Matesaktesak** [comment] 2024-09-24 20:11
@Zvonimir-FUTO how exactly is this a duplicate of #116 ? The topics see nothing alike - one is referring to vertical videos not being vertical, while this one talks about automatically downloading playlists. I ask for this issue to be kept open - I know there is a lot to do, but this is a very reasonable feature request. If I'm missing something, I'll of course apologize, just LMK. Thanks

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 20:15
> @Zvonimir-FUTO how exactly is this a duplicate of #116 ? The topics see nothing alike - one is referring to vertical videos not being vertical, while this one talks about automatically downloading playlists. I ask for this issue to be kept open - I know there is a lot to do, but this is a very reasonable feature request. If I'm missing something, I'll of course apologize, just LMK. Thanks

You are completely right it has nothing to do with 116 but it will be resolved through #157 where you also commented already.
I must have copied the wrong number... Getting lost between these 800 issues :)

**Comment by Matesaktesak** [comment] 2024-09-24 20:36
Right 😅 Thank you very much for maintaining this repo, it must be quite crazy managing so many requests. I love the app, you are doing great work!
