### ISSUE TITLE
Age Restricted videos are view restricted

### ISSUE THREAD

**Issue by Kelogens** [futo-org/grayjay-android#1423] opened 2024-10-19 21:30 UTC
### What happened?

Age restricted videos are being refused. Downloads are additionally impossible to perform. Despite me being logged in, I have to resort to using random website video downloaders to get the content I wanted to watch. In an attempt to sidestep this, I've enabled Login for Channels, video details, login fallback, allowing age restricted and controversial restricted, etc. I turned off sponsorblock and youtube dislike. No dice.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

208

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
[Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl')(3475)[58-59]

Failed to fetch details for download [Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl')(3475)[58-59]
```

**Comment by Kelogens** [comment] 2024-10-19 21:33
This appears to be a widespread issue that's repeating despite updates to the plugin, and/or app. Videos that are age restricted are being held back completely. I went through additional testing to see if my router had anything to do with it. No.. I went to a fast food place for different results off their internet. 

I went and used a vpn on the same location for a difference. Nada. I feel like it's safe to say YouTube made some changes...

**Comment by kj2900** [comment] 2024-10-22 09:07
It's weird thst you cannot watch age restricted videos while you are logged in i reported the same issue a few days ago i hope this will get a fix whether you are logged in or not

**Comment by support-grayjay** [comment] 2024-10-28 18:46
Could you provide some examples of this? I tested with [this video](https://www.youtube.com/watch?v=I1o4MLTHVw0) and couldn't reproduce this.

**Comment by Kelogens** [comment] 2024-10-28 19:40
Yeah no problem. It's a bit more of a hunt but when I looked up Donut Operator and went down the list, eventually one of the blurred videos would show up with this error, though the majority is just showing a notification saying fallback to UMP. 

https://www.youtube.com/watch?v=v07Zi8mAhjY
https://www.youtube.com/watch?v=uxSGIIrg-_c
https://www.youtube.com/watch?v=71wdrhKzuys
https://www.youtube.com/watch?v=bQA2AZo_Ewc

Here are a few videos in which appear to be age restricted and have this error. I hope it helps!
![Screenshot_20241028-143639](https://github.com/user-attachments/assets/c0fe0267-918c-41e4-aca0-097a15a8c4d1)

**Comment by TinyHuman99** [comment] 2024-10-28 23:11
Here is another video where I have this same issue and error message: https://www.youtube.com/watch?v=NkARD8oTzOM

**Comment by support-grayjay** [comment] 2024-10-29 18:39
Thank you guys for providing more examples. I'm able to reproduce this and we will look into this issue.

**Comment by Philippe-Choquette** [comment] 2024-11-12 07:36
I get it with this popular Kurzgesagt video:
https://youtu.be/oTx-GSF3cts?si=XcgLj7hxDAEtv1j9

**Comment by Kelogens** [comment] 2024-11-12 07:47
It has a suicide tag on it. It's struck by YouTube..
Checked it, and yeah it doesn't work for grayjay regardless of login. I suspect a barrier from the api here

**Comment by flabdablet** [comment] 2024-11-21 11:18
Another blocked video: https://www.youtube.com/watch?v=jqeqrD7_PeU

**Comment by Zvonimir-FUTO** [comment] 2024-11-26 14:27
All workarounds for age restricted/controversial video retrieval without login have been removed. We will improve error message for this.
You should be able to see watch the video while logged in. Does it not work when logged in as well?

**Comment by Philippe-Choquette** [comment] 2024-11-26 16:01
> Does it not work when logged in as well?

@Zvonimir-FUTO
I've logged in with my Google account to make the test. Despite the fact that the account has a birthdate which implies that I'm over 18, and that I can play all the videos given as example in the issue's comments above on the YouTube app/website, it doesn't work through Grayjay.

I've made attempts with the "Provide YouTube Activity" setting of the YouTube plugin in both enabled and disabled status, with no change.

------

In the screen recording below, you can see the current settings for the YouTube plugin on my end, and an attempt to play the video I provided as example in another comment:
https://github.com/user-attachments/assets/4ae63c25-cc5f-4146-a375-698d156a06b0

And in the following, an attempt with another video:
https://github.com/user-attachments/assets/8f74ab3c-7da6-4f67-8a85-514ba0137283

**Comment by Zvonimir-FUTO** [comment] 2024-11-26 16:09
@Philippe-Choquette I can see you are on 215 version, can you update to 216 and try again?

**Comment by Philippe-Choquette** [comment] 2024-11-26 16:36
> @Philippe-Choquette I can see you are on 215 version, can you update to 216 and try again?

That did it! Thanks FUTO team!

I'm assuming that you just pushed the update because it wasn't suggested to me through my attempts earlier.

------

As a side note:
I signed out from my Google account to see what would happen if I try to play one of such videos. I see that you've added an overlay that requests the user to sign in and a button to do so. I tapped the button and signed in, but all it did was bring back the same overlay. I signed in again, and the video started playing in the background. However, a new overlay covered it stating that no sources are available for this request or something like that. So this flow might have to be polished.

**Comment by Zvonimir-FUTO** [comment] 2024-11-26 16:39
Thank you for your feedback and testing. We will look into that flow a bit more. Closing this issue.

**Comment by FakeMichau** [comment] 2024-11-28 02:52
Few issues I noticed:
- Most videos are still unplayable for me, even though I'm logged in and using the version 216. Looks the same as on the clip sent few messages earlier.
- I'm not being prompted to enable "Allow Age Restricted" or "Allow loginfallback" and instead I'm stuck in a loop telling me that age restricted video requires login, even though I did log in, just didn't have those options enabled.
- Controversial videos seem to work but it spams the prompts a bit about trying to bypass at first

That's how the usual error looks like
![Screenshot_20241128_032618_Grayjay](https://github.com/user-attachments/assets/40153306-2dbc-46e4-b5c7-4d74c683237f)

If I log in using this new prompt I also get this 
![Screenshot_20241128_034524_Grayjay](https://github.com/user-attachments/assets/22e309c1-76fa-4228-aa4b-572a1cf0e6bd)

**Comment by Kelogens** [comment] 2024-11-28 02:55
May I get a video link to test this out myself?

**Comment by FakeMichau** [comment] 2024-11-28 03:00
All videos sent in this issue have this behavior, expect for Kurzgesagt's video which was working for me but now gives this "No source enabled..." error

**Comment by Kelogens** [comment] 2024-11-28 03:07
https://www.youtube.com/watch?v=bQA2AZo_Ewc

Controversial video, bypassing.. 
bypass failed, trying login fallback.

Failed to load video plugin. Re-creatable but a bit harder to find case by case. It took four links.

**Comment by PhilC813** [comment] 2024-11-28 09:53
I compiled the following table, which includes all the videos that have been problematic, along with my results. It will be kept up to date.

<table>
	<theader>
		<tr>
			<th colspan="100%">Testing Parameters</th>
		</tr>
	</theader>
	<tbody>
		<tr>
			<th rowspan="3">App</th>
			<th colspan="2">Version Code</th>
			<td>264</td>
		</tr>
		<tr>
			<th colspan="2">Version Name</th>
			<td>264</td>
		</tr>
		<tr>
			<th colspan="2">Version Type</th>
			<td>release</td>
		</tr>
		<tr>
			<th>Plugin</th>
			<th colspan="2">Version</th>
			<td>216</td>
		</tr>
	</tbody>
	<theader>
		<tr>
			<th colspan="100%">Entries</th>
		</tr>
	</theader>




	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;1<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2442467674">Comment</a><br>@Kelogens</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>Cops Respond to INSANE Ambush</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Donut Operator</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=v07Zi8mAhjY">https://www.youtube.com/watch?v=v07Zi8mAhjY</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟥</th>
			<td>[Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl') (3699)[58-59]</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;2<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2442467674">Comment</a><br>@Kelogens</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>Nashville School Shooting Breakdown</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Donut Operator</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=uxSGIIrg-_c">https://www.youtube.com/watch?v=uxSGIIrg-_c</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟥</th>
			<td>[Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl') (3699)[58-59]</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;3<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2442467674">Comment</a><br>@Kelogens</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>ANGRY soldier attacks skateboarder for no reason at all</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Donut Operator</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=71wdrhKzuys">https://www.youtube.com/watch?v=71wdrhKzuys</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟥</th>
			<td>[Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl') (3699)[58-59]</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;4<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2442467674">Comment</a><br>@Kelogens</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>Cops Politely Discourage Road-Raging Grandpa</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Donut Operator</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=bQA2AZo_Ewc">https://www.youtube.com/watch?v=bQA2AZo_Ewc</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟥</th>
			<td>[Youtube] Cannot read properties of undefined (reading 'serverAbrStreamingUrl') (3699)[58-59]</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;5<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2442843874">Comment</a><br>@TinyHuman99</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>RAP WORLD</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Conner O'Malley</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=NkARD8oTzOM">https://www.youtube.com/watch?v=NkARD8oTzOM</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟩</th>
			<td>—</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;6<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2469797290">Comment</a><br>@PhilC813</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>This Video Might Save 58 Lives Next Week</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>Kurzgesagt – In a Nutshell</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://youtu.be/oTx-GSF3cts?si=XcgLj7hxDAEtv1j9">https://youtu.be/oTx-GSF3cts?si=XcgLj7hxDAEtv1j9</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟩</th>
			<td>—</td>
		</tr>
	</tbody>

	<tbody>
		<tr>
			<th rowspan="100%" align="center">Video #&#65279;7<br>- - -<br><a href="https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2490843005">Comment</a><br>@flabdablet</th>
		</tr>
		<tr>
			<th rowspan="3">Details</th>
			<th>Title</th>
			<td>The WORST FIGHT IN NBA HISTORY?! 'Malice at the Palace' | Iconic Moments</td>
		</tr>
		<tr>
			<th>Creator</th>
			<td>ESPN Throwback</td>
		</tr>
		<tr>
			<th>URL</th>
			<td><a href="https://www.youtube.com/watch?v=jqeqrD7_PeU">https://www.youtube.com/watch?v=jqeqrD7_PeU</a></td>
		</tr>
		<tr>
			<th>Status</th>
			<th>🟩</th>
			<td>—</td>
		</tr>
	</tbody>
</table>

**Comment by Zvonimir-FUTO** [comment] 2024-11-28 16:17
Thank you @PhilC813 for giving many examples. We found the issue and fixed it in the v217 of Youtube. Please update and check. Keep in mind that login is still required. Closing issues.

**Comment by FakeMichau** [comment] 2024-11-28 16:27
For me the 217 didn't change anything. Videos that didn't work still don't work. The error message is also the same.

**Comment by Zvonimir-FUTO** [comment] 2024-11-28 16:51
@FakeMichau Can you please confirm you have enabled "Allow Age Restricted" and "Allow Controversial Restricted" in Youtube settings and that you are logged in?

**Comment by FakeMichau** [comment] 2024-11-28 17:04
Yes I do.
![Screenshot_20241128_180305_Grayjay](https://github.com/user-attachments/assets/dd26c2f2-fb6d-4709-b815-0f149e519f46)

**Comment by PhilC813** [comment] 2024-11-29 06:25
I can confirm that all videos are now playable on my end.

------

@FakeMichau Are you absolutely sure that you can play those same videos on the YouTube website/app using the *same* Google account you're using in Grayjay?

Because it just so happens that the only video that you can play, the one from Kurzgesagt, is the only one that isn't age-restricted; all others are. So I suspect that the DOB (date of birth) in the Google account you're using is under what Google considers age of majority.

Do you mind sharing what country you're in? Maybe it could also have something to do with YouTube's policies being different in your jurisdiction.

**Comment by FakeMichau** [comment] 2024-11-29 11:18
I'm glad some don't have this issue anymore but as I stated previously, beyond any doubt, it's not an issue with the account. I've been using that account for over a decade in the browser and the official YouTube app without such issues, and it still works just fine. 

On a newer account those videos seem to work so it's likely the plugin not handling something properly about this account, it's a brand account that went through many changes as YouTube implemented changes so I'm not hugely surprised.
Or it could be Google testing something again.

If the devs need some logs, some extra info then I'm open to providing that and helping to figure out the underlying issue.

**Comment by Allvaldrsson** [comment] 2024-12-13 07:46
I've been experiencing this issue for about a month, as far as I've noticed. 

Can confirm that "Allow Age Restricted" is toggled ON. The Authentication Login option takes me to my YouTube account settings which offers no solution. Cancelling out of the Authentication reveals the "No source enabled" error. I have no problems watching the restricted videos in a browser or within the official YouTube app 

GrayJay v268
YT Source v218

![Screenshot_20241213-013118](https://github.com/user-attachments/assets/75316201-c1c3-4968-9951-0efbaa6112e5)
![Screenshot_20241213-013403](https://github.com/user-attachments/assets/8ca76693-d2cb-41a5-bb61-eff5e40a1666)

**Comment by Zvonimir-FUTO** [comment] 2024-12-13 12:12
@Allvaldrsson can you please confirm you are logged in to Youtube?

**Comment by Allvaldrsson** [comment] 2024-12-13 16:03
@Zvonimir-FUTO 

After selecting "Login" on the "Authentication" prompt as seen above, I'm taken to the following screen:

![Screenshot_20241213-100013](https://github.com/user-attachments/assets/48602ed7-bb6b-4123-b291-37aaec120e16)

**Comment by Zvonimir-FUTO** [comment] 2024-12-13 17:02
Here you should select your channel just there where you censored it. This is youtube's login flow and we can't change that.

**Comment by Allvaldrsson** [comment] 2024-12-13 17:13
Ah, success! That's not very intuitive of them but what do you expect. Thank you!

**Comment by Kelogens** [comment] 2024-12-13 17:19
Yeah YouTube doesn't make it seamless

**Comment by Zvonimir-FUTO** [comment] 2024-12-13 17:28
Closing this issue since the root cause of original issue was fixed.

@FakeMichau please open a new issue for yours which seems to be having a different cause and is buried behind the comments in this issue.

**Closed by Zvonimir-FUTO** 2024-12-13 17:28 UTC
Labels: Bug, Youtube, Reproducible
