### ISSUE TITLE
App forgets video position

### ISSUE THREAD

**Issue by RedStealthDev** [futo-org/grayjay-android#208] opened 2023-11-07 06:26 UTC
With background behavior set to none if I leave and come back to the app the video I was watching, has either restarted from the beginning or starts ca 5 seconds in. This causes a need to search through the video to find the location that I was at.

Edit.1:  I just remembered that this also causes the queue to be removed.

App version: arm64 release 190
Android version: 13
Device: Asus ROG phone 6 pro

If you nead more info yust ask.

**Comment by palmerbomber1** [comment] 2023-11-07 07:56
Question for you, is there not a "return to position XX:XX " at the top of the video field when you reopen the video? I just watched 2 minutes of a video, restarted my phone and opening the video again i got a button at the top to return to where i was.

**Comment by RedStealthDev** [comment] 2023-11-07 13:26
No sadly i dont i do however get the return to x if i watched a part of a video fully closed the app and opened it again or if u partially watch a video go to another one and return.
And that matches what you're saying but my issue comes from leaving the app while its still on in the background and then coming back.

**Comment by koen-futo** [comment] 2023-11-09 12:19
I will investigate, thanks for the report.

**Comment by koen-futo** [comment] 2023-11-09 12:35
I did some initial investigating, I did not manage to reproduce this issue. I tried with several different background behaviours. I tried with none and then leading it stopped in the background for a while and returning to the app. I tried running lots of background tasks to try and get the activity disposed, nothing seems to reproduce the issue you have for me.

Could you attach a video or steps so I can reproduce this issue?

**Comment by Kaliaila** [comment] 2023-11-09 18:37
I have ran into this and think that what is actually happening is that the toast message with the link to resume to whatever timestamp is disappearing before it can be seen. Maybe because another part of the screen is touched or who knows why, so that the entire message is missed. 

On a related note, is there a reason why you guys are having it default to restarting the video rather than resuming? I ask because pretty much all other platforms do it the opposite way to what you do and it is considerably easier for the user to manually restart the video than it is to find the spot they are resuming from.

**Comment by koen-futo** [comment] 2023-11-10 11:17
The reason the default is what it is, is because it is hard to distinguish what video you would want to always start from the beginning (like a music video or music compilation video) and what videos you would want to continue where you last left off (like a podcast).

I experimented while developing with having the history bar show on every single video and if history was available to continue at that moment in the video, but it just was more confusing then anything and for my personal use case which is doing workouts it almost never ended up being what I needed.

At this moment I chose for only when accessing the video through the history tab, will it continue where you left off automatically.

If all that is going on is the message disappearing too quickly, I could add a permanent "continue at" in the video controls which shows once the other continue at goes away.

**Comment by RedStealthDev** [comment] 2023-11-12 08:26
https://github.com/futo-org/grayjay-android/assets/64406606/19e93dc3-acbe-493d-b7d6-6ef6be17e747

Here you go a video of the issue. The same thing happens if i leave and enter the app via the switch app button or even opening a notification and then going back to the app.

And also i would love a toggle in the settings that turns on the always return to the last point for all videos thing you were talking about.

**Comment by koen-futo** [comment] 2023-12-01 10:56
Thank you for the video, I will have another look

**Comment by Zvonimir-FUTO** [comment] 2024-09-24 18:41
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Closed by Zvonimir-FUTO** 2024-09-24 18:41 UTC
Labels: Bug, UI/UX
