### ISSUE TITLE
Refreshing desktop app with F5 causes 404 error

### ISSUE THREAD

**Issue by TheDeviantCrafter** [futo-org/grayjay-android#1673] opened 2024-12-28 16:07 UTC
### What happened?

![image](https://github.com/user-attachments/assets/515e7047-ca00-4c36-9427-0b3a2aa0f7fc)

I expected Grayjay to refresh the current tab similar to pulling down to refresh the Android app.

### Grayjay Version

2

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Are you using a VPN?

No

**Comment by Zvonimir-FUTO** [comment] 2024-12-28 16:08
Duplicate of https://github.com/futo-org/Grayjay.Desktop/issues/25

**Closed by Zvonimir-FUTO** 2024-12-28 16:08 UTC
Labels: Bug, Duplicate, Desktop
