### ISSUE TITLE
[Issue] importing playlists

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#349] opened 2023-11-21 18:01 UTC
I know you guys got bored im continuously mention about tthaat but, its very important as for me to access those playlists

**Comment by koen-futo** [comment] 2023-11-21 19:27
I will look into this soon.

**Comment by HafizBeyy** [comment] 2023-11-22 07:22
> I will look into this soon.

Thanks! 🙏🙏

**Comment by Ser-Bul** [comment] 2024-06-12 10:15
Duplicate of https://github.com/futo-org/grayjay-android/issues/85

**Closed** 2024-06-19 21:44 UTC
